/* =========================================================
   CONVERSATIONS, as small directed threads.
   A topic is a little graph, not a bag of lines:
     q: openers [type, text, key]. type = what kind of question it is (yn, when, where, what, how, who, or say for a
        statement). key = WHICH question it is: openers with the same key ask the same thing, and nobody asks a key they
        already know the answer to. Without a key, the type is the key.
     a: answers, looked up by key first, then by type, so a reply always answers what was actually asked.
        "text|tag tag" marks what an answer establishes (yes, no, unsure, ask...). An answer ending in "?" is tagged ask
        automatically and is only used when the topic has a follow-up that picks it up.
     n: follow-ups. { k: 'keys it can follow' (or '*'), t: 'answer tags it needs' (any of them; empty = any answer),
        say: one line or a few ways of saying it, re: the replies (tagged the same way), then: deeper follow-ups that can
        only come after THIS exchange, by: 'a' | 'b' who says it (default: whoever didn't speak last) }.
        A follow-up can only follow the questions and answers it names: "We're gonna be late" follows "About four",
        never "Who are you texting?".
     back: how someone brings it up again once the danger has passed ("text|tag" = only if that was established).
     flags: out (outdoor maps only), dark / light (only at that time), not: 'season ids', needs: 'dog' (the one
        answering has a dog with them), fact(): a tag the world decides (the pizza place is open or it isn't).
   Placeholders: {time} the time spoken roughly, {nexthour}, {today} (today / tonight), {here} (out here / in here).
   "#tag" on a line opens a thread something later can close ("I swear something's weird tonight.#weird" -> "SEE?").
   ========================================================= */
const TALK = {
  generic: [
    { id: 'phone', q: [['say', "My phone's almost dead.", 'dead'], ['say', "Ugh, my battery's at like five percent.", 'dead'], ['yn', 'You got a charger on you?', 'charger'], ['yn', 'Can I borrow your charger later?', 'charger']],
      a: { dead: ['Mine too.|same', "Should've charged it last night.|scold", "There's a charger in the car.|car", 'Put it on low power mode.|tip', 'Classic.|tease'],
           charger: ['In the car, yeah.|yes car', 'Nope, sorry.|no', 'Not one that fits yours.|no', 'Yeah, remind me later.|yes', "Mine's broken, so no.|no"] },
      n: [{ k: 'dead charger', t: 'car', say: ['Can we grab it after?', 'Remind me to grab it.'], re: ['Yeah, sure.', 'If you remind me.'] },
          { k: 'charger', t: 'yes', say: ["You're a lifesaver.", 'Thank you. Seriously.'], re: ['I know.', 'You owe me.', 'Yeah, yeah.'] },
          { k: 'dead charger', t: 'no same tip', say: 'I need it for the bus times.', re: ['Just ask someone.', 'The bus is late anyway.', 'I know them by heart. Kind of.'] },
          { k: 'dead', t: 'scold tease', say: ['Okay, thanks, mom.', 'Not helpful.'], re: ['Just saying.', 'Someone has to.'] }] },
    { id: 'tired', q: [['say', "I'm so tired.", 'tired'], ['say', 'I could fall asleep standing up.', 'tired'], ['yn', 'Did you sleep at all last night?', 'slept'], ['how', 'How are you even awake right now?', 'awake']],
      a: { tired: ['Same.|same', 'Go to bed earlier, then.|scold', 'Coffee. Seriously.|tip', 'You say that every day.|tease', 'Long week?|ask'],
           slept: ['Like four hours.|bad', 'Not really, no.|bad', 'Barely.|bad', 'Yeah, actually. First time in ages.|good'],
           awake: ['Spite.', 'Three coffees.', "I'm not awake.", 'Honestly? No idea.'] },
      n: [{ k: 'tired', t: 'ask', say: ["Don't even ask.", 'The worst.'], re: ['Hang in there.', "It's almost over.", 'Yeah. Same.'] },
          { k: 'tired slept', t: 'scold same bad', say: 'The neighbors were up till two again.', re: ['Call someone about it.', "That's so annoying.", 'Doing what?'],
            then: [{ t: 'ask', say: ['Moving furniture, I think. At two.', 'Some party. Again.'], re: ['Unbelievable.', 'Call the landlord.'] }] },
          { k: 'slept', t: 'good', say: ['Lucky.', 'Must be nice.'], re: ["I know, right?|rq", "Doesn't happen often."] },
          { k: 'tired awake', say: "I'm going to bed the second I get home.", re: ['Same.', "You won't.", "No you're not."] }] },
    { id: 'time', q: [['what', 'What time is it?', 'time'], ['what', 'You got the time?', 'time'], ['yn', 'Is it {nexthour} yet?', 'hour']],
      a: { time: ['{Time}.|known', 'About {time}.|known', 'No idea, my phone died.|unknown', 'Like {time}, I think.|known'],
           hour: ['Almost.|known', "Not yet. It's {time}.|known", "I don't know. My phone died.|unknown"] },
      n: [{ k: '*', t: 'known', say: ["We're gonna be late.", 'We should get going.'], re: ['Yeah, we should move.', 'Then walk faster.', "We've still got a few minutes."] },
          { k: '*', t: 'known', say: ['Okay. We have a bit, then.', 'Good. No rush.'], re: ['Relax, yeah.', "Don't get comfortable."] },
          { k: '*', t: 'unknown', say: ['Useless.', 'Great. Neither of us knows.'], re: ["Hey, it's not my fault.", 'Ask someone else, then.'] }] },
    { id: 'hungry', q: [['say', "I'm starving.", 'hungry'], ['yn', 'You hungry?', 'hungry?'], ['what', 'What do you want to eat later?', 'food']],
      a: { hungry: ['Same.|same', 'Already?|tease rq', "There's a granola bar in my bag.|offer", 'We can grab something soon.|plan'],
           'hungry?': ['Yeah, kinda.|yes', 'Not really.|no', 'A little.|yes', 'I could eat.|yes'],
           food: ['Burgers sound good.|picked', "I don't care. You pick.|pick", 'Something cheap.|cheap', 'Maybe tacos?|picked rq'] },
      n: [{ k: 'hungry', t: 'offer', say: ['Oh my god, yes. Please.', "You're the best."], re: ["It's a little squished.", "Here. Don't say I never do anything."] },
          { k: 'hungry hungry?', t: 'same yes plan', say: 'Burgers after this?', re: ["I'm down.", 'Again?|rq', 'Sure, why not.'] },
          { k: 'food', t: 'pick cheap', say: ['Okay. Tacos.', 'Fine. Pizza.'], re: ['Works for me.', 'Sold.'] },
          { k: 'food', t: 'picked', say: ['Yeah, I could go for that.', 'Sold.'], re: ['Good. Decided.', 'See? Easy.'] },
          { k: 'hungry', t: 'tease', say: 'I skipped lunch.', re: ["Well, that's on you.", 'Why would you do that?'],
            then: [{ t: 'ask', say: ["Didn't have time.", 'Forgot, honestly.'], re: ['Eat something, seriously.', 'Classic.'] }] }],
      back: ["Okay, I'm definitely hungry now.", 'So... burgers still happening?|yes'] },
    { id: 'weather', out: true, q: [['yn', "Think it's gonna rain?", 'rain'], ['say', "Sky looks like it's about to open up.", 'sky'], ['say', 'Weather turned fast.', 'turned']],
      a: { rain: ['Probably.|yes', 'Hope not.|unsure', 'Looks like it.|yes', "I didn't check.|unsure"], sky: ['Yeah, looks like it.|agree', 'We should probably head in soon.|agree', 'Great. Perfect.|agree'], turned: ['Yeah, it changed quick.|agree', 'I noticed.|agree', 'Of course it did.|agree'] },
      n: [{ k: '*', t: 'yes agree', say: "I didn't bring a jacket.", re: ['Neither did I.', 'You can borrow mine if it starts.', "Then let's not stay out too long."] }] },
    { id: 'weekend', q: [['what', 'What are you doing this weekend?', 'plans'], ['yn', 'You doing anything this weekend?', 'plans'], ['say', 'I need this weekend so bad.', 'need']],
      a: { plans: ['Probably sleeping.|free', "My cousin's wedding.|busy", 'Nothing, hopefully.|free', "I'm moving, unfortunately.|busy", 'Working, unfortunately.|busy'],
           need: ['Same.', 'Almost there.', 'Seriously.', 'This week has been dragging.'] },
      n: [{ k: 'plans', t: 'free', say: 'Want to do something Saturday?', re: ['Yeah, what did you have in mind?', 'Maybe. Text me later.', 'Sure.'],
            then: [{ t: 'ask', say: ['Movies, maybe?', "I don't know. Something cheap."], re: ["I'm in.", 'Sounds good.'] }] },
          { k: 'plans', t: 'busy', say: ['Ugh. Have fun with that.', 'That sounds like a lot.'], re: ['It is.', "Thanks. I'll survive."] },
          { k: 'need', say: 'Two more days.', re: ["Don't count. It makes it worse.", 'Two and a half.'] }] },
    { id: 'weird', q: [['say', "I swear something's weird {today}.#weird", 'weird'], ['say', 'Does it feel weird {here} or is that just me?#weird', 'weird'], ['say', 'Got a bad feeling about today.#weird', 'weird']],
      a: { weird: ["It's just you.|dismiss", 'You always say that.|dismiss', 'Yeah, actually. A little.|agree', 'Relax.|dismiss', 'What kind of weird?|ask'] },
      n: [{ k: 'weird', t: 'ask', say: ['I dunno. Too quiet.', "Like something's watching us."], re: ["You're being paranoid.", "Okay, now I'm creeped out.", "Don't say that."] },
          { k: 'weird', t: 'agree', say: "Right? It's too quiet.", re: ["Let's not hang around, then.", "Okay, stop, you're freaking me out."] },
          { k: 'weird', t: 'dismiss', say: ["Fine. Don't believe me.", "Whatever. I'm just saying."], re: ['I won\'t.', 'Noted.'] }] },
    { id: 'work', q: [['how', "How's work?", 'work'], ['yn', 'You still at that place?', 'still']],
      a: { work: ["Don't ask.|bad", 'Same as always.|meh', 'Thinking of quitting.|quit', 'Got promoted. Kind of.|promo'], still: ['For now.|meh', 'Yeah. Unfortunately.|bad', 'Thinking of quitting.|quit'] },
      n: [{ k: '*', t: 'quit', say: ['Seriously? To do what?', 'Wait, really?'], re: ['No idea yet.', "Anything. I'll figure it out."] },
          { k: 'work', t: 'promo', say: ['Kind of?', 'What does "kind of" mean?'], re: ['Same job, new title, no raise.', 'I get a desk by the window now.'] },
          { k: '*', t: 'bad meh', say: ['That bad, huh?', 'Same boss?'], re: ['Same boss.', "It's fine. It's not fine."] }] },
  ],
  field: [
    { id: 'lost', q: [['yn', 'Are we lost?', 'lost'], ['where', 'Which way did we come in?', 'way'], ['where', 'Where was that gate again?', 'way']],
      a: { lost: ['Maybe a little.|yes', 'No, I know where we are.|no', 'I think so.|yes', 'Not lost. Just... turned around.|yes'], way: ['Back that way, I think.|guess', 'Past the fence.|guess', 'Toward the tree line.|guess', 'Honestly, I lost track.|unknown'] },
      n: [{ k: '*', t: 'no guess', say: 'You said that ten minutes ago.', re: ["I know. I'm less confident now.", 'Then you pick a direction.', 'Okay, yeah, we might be lost.'] },
          { k: '*', t: 'yes unknown', say: ['Great. My feet are killing me.', 'Perfect.'], re: ['We can stop for a minute.', "We're finding the way back first."] }],
      back: ['Okay... where was that gate again?'] },
    { id: 'deer', q: [['yn', 'Seen any deer yet?', 'seen'], ['say', 'There were deer here last time.', 'last']],
      a: { seen: ['One, by the trees.|yes', 'Not yet.|no', "You're too loud for deer.|tease", 'Something big ran off earlier.|maybe'], last: ['Maybe they moved.|doubt', 'Shh, then.|hush', 'At dusk, probably.|dusk'] },
      n: [{ k: '*', t: 'no doubt tease', say: "They're usually out around sunset.", re: ['Then we wait.', "We'll be gone by then."] },
          { k: 'seen', t: 'yes maybe', say: ['Where? Show me.', 'Seriously? Which way?'], re: ["Over there. It's gone now.", 'Too late. It ran.'] }] },
    { id: 'stars', out: true, dark: true, q: [['say', 'You can actually see stars {here}.', 'stars'], ['yn', 'Is that bright one a planet?', 'planet']],
      a: { stars: ['Yeah. No city lights out here.', "It's nice, actually.", 'Way more than you can see in town.'], planet: ['Might be Venus.|maybe', "I think that's a plane.|plane", 'No idea. Could be.|maybe'] },
      n: [{ k: 'planet', t: 'maybe', say: "It's blinking.", re: ["Then it's probably a plane.", "Yeah, okay, that's a plane.", "Planes blink. Planets don't."] },
          { k: 'planet', t: 'plane', say: ["Oh. Yeah, it's moving.", "Huh. You're right."], re: ['Told you.'] }] },
    { id: 'fence', q: [['yn', 'Are we even allowed past that fence?', 'allowed'], ['say', 'I think this is private land.', 'private']],
      a: { allowed: ['Probably not.|no', "Nobody's gonna check.|whatever", 'There was a sign.|sign', "Didn't see a sign.|whatever"], private: ['So?|whatever rq', "Then let's not get caught.|whatever", "It's a field. Who cares.|whatever"] },
      n: [{ k: 'allowed', t: 'sign', say: 'What did the sign say?', re: ["Didn't read it.", 'No trespassing, I think.', 'Something about dogs.'] },
          { k: '*', t: 'whatever no', say: ["If a farmer shows up, I'm blaming you.", 'Okay, but if we get yelled at...'], re: ['Fine by me.', 'Deal.'] }] },
    { id: 'car', q: [['yn', 'Did you lock the car?', 'locked'], ['where', "Where'd we leave the car?", 'where']],
      a: { locked: ['I think so.|unsure', 'Yeah.|yes', 'You had the keys.|you'], where: ['By the gate.|known', 'Down by the road.|known', 'I thought you knew.|unknown'] },
      n: [{ k: 'locked', t: 'you', say: ['I did not have the keys.', 'No I didn\'t.'], re: ['Check your pocket.', 'Then who did?|rq'] },
          { k: 'locked', t: 'unsure', say: 'You think so?', re: ["I'm like eighty percent sure.", "It's fine. Nobody's out here."] },
          { k: 'where', t: 'unknown', say: ['Great.', 'Neither of us knows where the car is.'], re: ["We'll find it.", 'It\'s a field. It\'s not hiding.'] }],
      back: ["...we should check if the car's locked."] },
  ],
  meadow: [
    { id: 'lake', not: 'winter', q: [['yn', 'You actually getting in?', 'in'], ['yn', 'Want to go in the lake?', 'in'], ['say', 'Lake looks nice {today}.', 'nice']],
      a: { in: ['Maybe in a minute.|maybe', "Yeah, but I'm not going past my knees.|yes", 'No chance.|no', 'Only if you go first.|dare'], nice: ['Yeah, it does.|agree', 'It looks freezing, though.|cold', 'Makes me want to jump in.|agree', 'Way nicer than last time.|agree'] },
      n: [{ k: 'in', t: 'maybe yes', say: "Think the water's cold?", re: ['Definitely.', 'Probably at first.', 'Only one way to find out.'] },
          { k: 'in', t: 'dare', say: ['Fine. Race you to the dock.', 'Deal. Last one in buys dinner.'], re: ["You're on.", "Wait, I didn't agree to that."] },
          { k: 'in', t: 'no', say: "Come on, it's nice.", re: ['Not happening.', "I'll watch. From here. Dry."] },
          { k: 'nice', t: 'cold', say: "It's not that cold.", re: ['Then you go first.', 'Sure it isn\'t.'] }] },
    { id: 'bugs', not: 'winter', q: [['say', "I should've brought bug spray.", 'spray'], ['say', 'Something keeps biting me.', 'bite'], ['yn', 'You got bug spray?', 'spray?']],
      a: { spray: ['Told you.|told', "It's the lake.|lake", 'They like you more than me.|tease'], bite: ["It's the lake.|lake", "Don't scratch it.|tip", 'They like you more than me.|tease'], 'spray?': ['In my bag. Somewhere.|yes', 'Ran out.|no', 'Yep. Hold still.|yes', 'Nope. Sorry.|no'] },
      n: [{ k: 'spray', t: 'told', say: 'You did not tell me.', re: ['In the car. Twice.', 'I definitely did.', 'Okay, maybe I thought it.'] },
          { k: 'spray?', t: 'yes', say: ['Thank you. Seriously.', "You're a hero."], re: ["Don't use all of it."] },
          { k: 'spray? bite', t: 'no tip lake', say: "I'm going to be one giant bite by tonight.", re: ['Probably.', 'Wear long sleeves next time.'] }] },
    { id: 'fire', q: [['say', "Fire's getting low.", 'low'], ['yn', 'Should we put more wood on?', 'wood'], ['who', 'Whose turn is it to get wood?', 'turn']],
      a: { low: ["I'll get some.|go", 'Let it go out.|let', 'In a sec.|later'], wood: ['Yeah, go for it.|yes', "Wood's all damp.|damp", "Let it die, I'm tired.|let"], turn: ['Yours.|you', 'Not mine, I went last time.|you', "Nobody's. Let it go out.|let"] },
      n: [{ k: '*', t: 'damp you later', say: "There's dry stuff under the tarp.", re: ['Then you get it.', 'Smart.', "Okay, fine, I'll go."] },
          { k: '*', t: 'let', say: ["It'll be freezing without it.", 'And then what, sit in the dark?'], re: ["Fine. I'll get some.", "We'll live."] }] },
    { id: 'trail', q: [['yn', 'Does this trail loop back?', 'loop'], ['how', 'How much longer is this trail?', 'long'], ['where', 'Where does this trail come out?', 'end']],
      a: { loop: ['Eventually.|yes', "It's supposed to.|yes", "No idea, I'm following you.|unknown"], long: ['Mile? Maybe two.|far', 'Not long.|near', 'Longer than you want.|far'], end: ['By the car park.|known', 'Back at the tents, I think.|known', 'No idea.|unknown'] },
      n: [{ k: 'loop', t: 'yes', say: 'The map said it loops.', re: ["The map's from 2009.", 'Then it loops.', 'Maps lie.'] },
          { k: '*', t: 'unknown', say: ["Great. We're following each other.", 'So nobody knows.'], re: ['Pretty much.', 'Adventure!'] },
          { k: 'long', t: 'far', say: 'My legs are not gonna make it.', re: ['They will.', 'We can sit at the next bench.'] }],
      back: ['So does this trail loop back or not?'] },
    { id: 'frogs', not: 'winter', q: [['say', 'The frogs are so loud {today}.', 'loud'], ['yn', 'Hear the frogs?', 'hear']],
      a: { loud: ['Means rain, I think.', 'I like it.', "I can't sleep with that.", "It's mating season or something."], hear: ['Hard not to.', "Yeah, it's nice.", 'Is that a frog? Sounded like a duck.|duck'] },
      n: [{ k: 'hear', t: 'duck', say: "It's definitely a frog.", re: ['A frog that quacks?|rq', 'If you say so.'] }] },
    { id: 'marsh', q: [['who', 'Who brought the marshmallows?', 'who'], ['yn', 'We still got marshmallows?', 'left']],
      a: { who: ['You did.|you', 'I did. You\'re welcome.|me', 'Nobody, apparently.|nobody'], left: ['In the cooler.|yes', 'Ate them.|ate', 'A few.|yes'] },
      n: [{ k: 'who', t: 'you', say: ['I did? Where are they, then?', 'Oh. Right. I did.'], re: ['In the cooler.', 'In your bag, genius.'] },
          { k: 'who', t: 'nobody', say: ["So no s'mores.", "Camping without marshmallows. Great."], re: ["No s'mores.", 'Next time.'] },
          { k: 'left', t: 'ate', say: ['You ate ALL of them?', 'Seriously?'], re: ['There were only six.', 'They were calling to me.'] },
          { k: 'left', t: 'yes', say: 'Dibs on the first one.', re: ["You're burning it again.", 'Fine.'] }] },
  ],
  town: [
    { id: 'pizza', fact: () => { const h = tod % 24; return h >= 11 && h < 22 ? 'open' : 'closed'; }, // the shop is open or it isn't; everyone agrees
      q: [['when', 'What time does that pizza place open?', 'opens'], ['yn', 'Is the pizza place open yet?', 'open'], ['yn', 'Think the pizza place is open?', 'open']],
      a: { opens: ['Eleven, I think.', "Pretty sure it's eleven.", 'Maybe noon?|rq', "I don't remember.|unknown"],
           open: ['I think so.|open', 'It should be by now.|open', 'It was open when I passed it earlier.|open', 'Probably not.|closed', 'It closes at ten, so no.|closed', 'Not sure. Check your phone.|unknown'] },
      n: [{ k: 'open', t: 'open', say: 'You want to grab some after this?', re: ['Yeah, I could eat.', 'Sure.', 'Not from that place.', "If you're buying."] },
          { k: 'open', t: 'closed', say: ['Ugh. Of course it is.', 'Seriously? Again?', "Great. Guess I'm starving."], re: ["There's always the corner store.", 'Tomorrow, then.'] },
          { k: 'opens', say: 'Their garlic knots are actually good.', re: ['Yeah, those are solid.', "They're okay.", 'Last time they messed up my order.'] }],
      back: ['So... pizza after this?|open'] },
    { id: 'traffic', q: [['say', "Traffic's been awful all day.", 'traffic'], ['how', 'How long did it take you to get here?', 'long'], ['how', "How'd you get here?", 'how']],
      a: { traffic: ['Yeah, the roadwork is killing it.|road', 'Tell me about it.|road', "It's been backed up since this morning.|road", "I should've walked.|road"],
           long: ['Almost forty minutes.|drove', 'Way too long.|drove', 'Like twenty minutes.|drove', 'Not long. I walked.|walked'],
           how: ['Drove. Parked a few blocks over.|drove', 'Took the bus.|drove', 'Walked.|walked', 'Got dropped off.|drove'] },
      n: [{ k: '*', t: 'road drove', say: "They've been digging up that road for months.", re: ['I know. It never ends.', 'Same stretch, too.', "I don't even know what they're fixing anymore."] },
          { k: 'long how', t: 'walked', say: ['Smart.', "Honestly, that's faster right now."], re: ["Yep. Legs don't get stuck in traffic."] }] },
    { id: 'store', fact: () => { const h = tod % 24; return h >= 7 && h < 23 ? 'open' : 'closed'; },
      q: [['yn', 'Corner store still open?', 'open'], ['what', 'Need anything from the store?', 'need'], ['when', 'When does the corner store close?', 'close']],
      a: { open: ['Should be.|open', 'Yeah, I think so.|open', 'It was open when I passed it.|open', 'I think it closed already.|closed', 'At this hour? No.|closed'],
           need: ['Milk, maybe.|milk', 'Chips.|item', "I'm good, thanks.|none", 'Batteries, actually.|item'], close: ['Eleven, I think.', 'Around eleven.', 'Pretty late.', "I don't remember."] },
      n: [{ k: 'open', t: 'open', say: "I'll run over in a bit. Want anything?", re: ['Something sweet.', 'Chips.', "I'm good."] },
          { k: 'open', t: 'closed', say: ['Great. There goes dinner.', 'Seriously?'], re: ["The gas station's open.", "Should've gone earlier."] },
          { k: 'need', t: 'milk item', say: ['Okay. Anything else?', 'Got it.'], re: ["That's it.", "No, that's all."] }],
      back: ['We still need that milk, by the way.|milk'] },
    { id: 'alley', q: [['yn', 'You still cut through that alley?', 'cut'], ['say', "Don't cut through the alley {today}.", 'warn']],
      a: { cut: ["Only when I'm late.|yes", "It's faster.|yes", 'Not after dark.|no'], warn: ['Why not?|ask', "It's fine.|dismiss", 'Okay, okay.|agree'] },
      n: [{ k: 'cut', t: 'yes', say: "It's gross back there.", re: ["It's two minutes faster.", 'Fair.', "Rats don't bother me."] },
          { k: 'warn', t: 'ask', say: ["It's dark and gross and there are rats.", "I just don't like it back there."], re: ['Fair.', 'Okay. Long way round.'] },
          { k: 'warn', t: 'dismiss', say: "I'm serious.", re: ["Okay, okay. I won't.", 'Fine.'] }] },
    { id: 'rent', q: [['yn', 'Did your rent go up too?', 'up'], ['say', 'Landlord raised the rent again.', 'raised']],
      a: { up: ["Don't. Don't start.|yes", 'Of course it did.|yes', "Mine's locked in till spring.|no"], raised: ['Again?|ask', "That's insane.|agree", 'Move in with me. Kidding.|joke'] },
      n: [{ k: 'raised', t: 'ask', say: 'Third time this year.', re: ['That has to be illegal.', 'Unreal.'] },
          { k: '*', t: 'agree yes', say: 'I might have to move.', re: ['Where?', "Don't, I'll miss you.", "Everywhere's the same."],
            then: [{ t: 'ask', say: ['No idea. Somewhere cheaper.', 'Back with my parents, maybe.'], re: ['Oof.', "That's rough."] }] },
          { k: 'up', t: 'no', say: 'Lucky.', re: ['Until spring.', "Don't jinx it."] }] },
    { id: 'parking', q: [['where', "Where'd you park?", 'where'], ['yn', 'Did you find parking?', 'found']],
      a: { where: ['Three blocks away.|far', "Didn't. I'm on a hydrant.|illegal", 'Behind the market.|near'], found: ['Took twenty minutes.|far', "Didn't. I'm on a hydrant.|illegal", 'Right out front, actually.|near'] },
      n: [{ k: '*', t: 'illegal', say: ['You are going to get towed.', 'On a hydrant?'], re: ["It's fine. Five minutes.", 'Worth it.'] },
          { k: '*', t: 'far', say: 'Parking here is a joke.', re: ['Every single time.', 'Should\'ve taken the bus.'] },
          { k: '*', t: 'near', say: ['Lucky.', 'How?'], re: ['Somebody pulled out right as I got there.', 'Skill.'] }] },
  ],
  maze: [
    { id: 'way', q: [['yn', 'Did we already go this way?', 'been'], ['where', 'Which way is out?', 'out'], ['say', 'I swear we passed this hedge.', 'been']],
      a: { been: ['Twice.|yes', 'No? Maybe.|unsure', 'Every hedge looks the same.|unsure', 'We did.|yes', "It's a maze. That's the point.|tease"], out: ['Left. I think.|guess', 'Right. Definitely right. Maybe.|guess', 'No idea.|unknown'] },
      n: [{ k: 'out', t: 'guess', say: 'You said that last time.', re: ['Then you pick.', "And I'll be right eventually.", 'Fine. Left.'] },
          { k: 'been', t: 'yes', say: ["So we're going in circles.", 'Great. Circles.'], re: ['Pretty much.', 'Left this time, then.'] }],
      back: ['Okay, seriously, which way is out?'] },
    { id: 'center', q: [['what', "What's even in the middle?", 'what'], ['yn', 'Is there a prize in the middle or something?', 'prize']],
      a: { what: ['A bench, probably.', "Nothing. It's a maze.", 'A statue, I heard.|statue'], prize: ['Bragging rights.', 'Pretty sure no.', 'A sense of accomplishment.'] },
      n: [{ k: 'what', t: 'statue', say: 'Of what?', re: ['Some guy on a horse.', "No idea. I just heard there's one."] }] },
    { id: 'creepy', dark: true, q: [['say', 'This place is creepy at night.#weird', 'creepy'], ['yn', 'Why did we come here after dark?', 'why']],
      a: { creepy: ["It's fine.|dismiss", "Yeah, it's a lot.|agree", "Don't start.|dismiss"], why: ['Tickets were cheaper.', 'It was your idea.|blame', 'Seemed fun at the time.'] },
      n: [{ k: 'why', t: 'blame', say: 'It was NOT my idea.', re: ['It was a hundred percent your idea.', 'Okay, it was kind of mine.'] },
          { k: 'creepy', t: 'agree', say: "Let's find the exit.", re: ['Working on it.', 'If there is one.'] }] },
    { id: 'signal', q: [['yn', 'Does your phone have signal?', 'signal'], ['yn', 'Can you call someone to find us?', 'call']],
      a: { signal: ['One bar.|weak', 'Nope.|no', "Battery's dead.|no"], call: ['Who would I even call?|no rq', 'One bar. Maybe.|weak', 'Nope. No signal.|no'] },
      n: [{ k: '*', t: 'no', say: ['Of course.', 'Great.'], re: ["We'll find it ourselves.", 'Should\'ve dropped breadcrumbs.'] },
          { k: '*', t: 'weak', say: 'Try the map, then.', re: ["It just shows a green square.", 'Loading. Still loading.'] }] },
  ],
  farm: [
    { id: 'fence', q: [['say', 'Fence by the pigs needs fixing.', 'fix'], ['yn', 'Did you see the fence by the pigs?', 'seen']],
      a: { fix: ['Which part?|ask', 'Again?|again', 'After lunch.|later', 'I fixed that last week. I thought.|again'], seen: ['The broken bit? Yeah.|yes', 'No, what happened?|ask', 'Saw it. Ignored it.|yes'] },
      n: [{ k: '*', t: 'ask', say: "The corner post. It's leaning.", re: ["I'll get the hammer.", 'Tomorrow.', "That post's been leaning for years."] },
          { k: '*', t: 'ask', say: 'The pigs knocked a board loose.', re: ["I'll get the hammer.", 'Again? Those pigs.'] },
          { k: 'fix', t: 'again', say: 'The pigs keep pushing on it.', re: ["They're smarter than us.", 'Then we need a new one.', "I'll move the trough."] },
          { k: '*', t: 'later yes', say: ['Today, though. Not next week.', 'Before they get out.'], re: ['Yeah, yeah.', 'Today. Promise.'] }] },
    { id: 'hens', q: [['say', 'Hens are restless today.', 'restless'], ['yn', 'Hear the chickens going off?', 'hear']],
      a: { restless: ['Storm coming, maybe.|storm', 'Or a fox.|fox', "They're always restless.|dismiss", "I'll check the coop.|check"], hear: ['Since this morning.|yes', 'Probably a fox.|fox', "I didn't hear anything.|no"] },
      n: [{ k: '*', t: 'fox yes storm', say: "Something's got them spooked.#weird", re: ["I'll take a look.", "They're chickens. Everything spooks them.", 'Lock the coop tonight.'] }] },
    { id: 'feed', q: [['yn', 'You feed the animals yet?', 'fed'], ['yn', 'Did everything get fed this morning?', 'fed'], ['who', 'Who fed the animals this morning?', 'who']],
      a: { fed: ['Yeah, this morning.|yes', 'Not yet.|no', 'I thought you already did.|confused', 'Most of them. I still need to do the pigs.|partial'], who: ['I did.|yes', 'Your dad did.|yes', 'I thought you did.|confused', 'Nobody yet, I think.|no'] },
      n: [{ k: '*', t: 'yes', say: "They're acting starved.", re: ['They always do.', "I'll check them again.", "Don't let them fool you."] },
          { k: '*', t: 'confused no', say: ['Well, somebody should.', 'Great. So nobody did.'], re: ["I'll do it now.", 'On it.'] },
          { k: 'fed', t: 'partial', say: "I'll do the pigs.", re: ['Thanks.', 'Watch the gate. It sticks.'] }] },
    { id: 'tractor', q: [['yn', 'Tractor still making that noise?', 'noise'], ['say', "Tractor's making that noise again.", 'again']],
      a: { noise: ['Worse.|worse', 'Kicked it. It helped.|kicked', "Haven't started it today.|unknown"], again: ['Kick it.|kick', "It's always done that.|dismiss", "I'll call the mechanic.|call"] },
      n: [{ k: 'noise', t: 'kicked', say: "That's your fix for everything.", re: ["It works, doesn't it?|rq", "And it's never failed me."] },
          { k: 'again', t: 'kick', say: "I'm not kicking it.", re: ['Then call someone.', 'Your loss.'] },
          { k: 'noise', t: 'worse', say: "We can't afford a new one.", re: ['I know.', 'Then it keeps making the noise.'] }] },
    { id: 'market', q: [['yn', 'We going to market Saturday?', 'going'], ['how', "How'd the eggs sell last week?", 'eggs']],
      a: { going: ['If the truck starts.|maybe', 'Yeah.|yes', "Can't. Vet's coming.|no"], eggs: ['Sold out by ten.|good', 'Not great.|bad', 'Better than the jam.|good'] },
      n: [{ k: 'eggs', t: 'good', say: 'Bring more this time, then.', re: ["The hens aren't laying that much.", 'Planning on it.'] },
          { k: 'eggs', t: 'bad', say: ['Huh. Weird.', 'Too much competition?'], re: ['New stall next to us.', 'Rained all morning.'] },
          { k: 'going', t: 'maybe', say: "It'll start.", re: ['It said that last week too.', 'Hope so.'] }] },
  ],
  park: [
    { id: 'dog', needs: 'dog', q: [['yn', 'Is he always this hyper?', 'hyper'], ['how', 'How old is he now?', 'age'], ['yn', 'Can I pet him?', 'pet']],
      a: { hyper: ['Every single day.', 'Only around ducks.', 'Only outside.'], age: ['Three.', 'Almost two.', 'Seven, believe it or not.|old'], pet: ['Sure, he loves it.|yes', 'He might lick you.|yes', 'He bites. Kidding.|joke'] },
      n: [{ k: 'age', t: 'old', say: 'Seven? He acts like a puppy.', re: ["He'll never grow up.", "Don't tell him."] },
          { k: 'pet', t: 'joke', say: 'Not funny.', re: ['A little funny.', 'Sorry. Go ahead.'] },
          { k: 'pet', t: 'yes', say: ['Hi! Hi, buddy!', "Oh, he's so soft."], re: ['He likes you.', "Don't let him jump."] }] },
    { id: 'ducks', q: [['say', 'Those ducks are following us.', 'follow'], ['yn', 'Did you bring anything for the ducks?', 'food']],
      a: { follow: ['They think we have food.', 'They do that to everyone.', "Ignore them or they'll keep following us."], food: ["No. We probably shouldn't feed them anyway.|nobread", 'I brought a little birdseed.|seed', 'Nope.|no', 'Yeah, but not bread.|nobread'] },
      n: [{ k: 'food', t: 'nobread', say: 'Why not bread?', re: ["It's not good for them, apparently.", "Birdseed's better.", 'I read it can mess with their diet.'] },
          { k: 'food', t: 'seed', say: ['Ooh, can I throw some?', 'Nice. Give me a handful.'], re: ['Here. Not all at once.', 'Sure.'] }] },
    { id: 'bench', q: [['yn', 'Wanna sit for a bit?', 'sit'], ['say', 'My legs are done.', 'legs']],
      a: { sit: ['Sure.|yes', 'In a sec.|yes', 'That bench is wet.|wet', 'If we can find a dry one.|wet'], legs: ['We walked like a mile.|tease', 'Sit, then.|sit', 'Same.|same'] },
      n: [{ k: 'sit', t: 'wet', say: ["It's fine. It's just a little damp.", "I don't care, I'm sitting."], re: ['Your jeans, your problem.', 'Gross. Okay.'] },
          { k: 'legs', t: 'tease', say: 'A mile is a lot.', re: ['It is not.', 'For you, maybe.'] }] },
    { id: 'jog', q: [['yn', 'You still running every morning?', 'still'], ['how', 'How many laps did you do?', 'laps']],
      a: { still: ['Most mornings.|yes', 'I walk now. It counts.|walk', 'Skipped today.|skip'], laps: ['Three.|yes', 'One and a half.|few', "Don't ask.|few"] },
      n: [{ k: 'still', t: 'walk', say: 'It totally counts.', re: ['Thank you.', "That's what I keep saying."] },
          { k: 'laps', t: 'few', say: ['Hey, half a lap is still a lap.', 'Better than me.'], re: ['Thanks. I think.'] },
          { k: 'still', t: 'skip', say: ['Rebel.', 'One day off is fine.'], re: ["It's been a week.", "That's me."] }] },
    { id: 'pond', q: [['say', 'Pond looks gross {today}.', 'gross'], ['yn', 'Are there fish in there?', 'fish']],
      a: { gross: ['Algae.|algae', "Don't touch the water.|warn", 'It always looks like that.'], fish: ['Some. Small ones.|yes', 'A turtle, I think.|turtle', 'Nothing alive in there.|no'] },
      n: [{ k: 'fish', t: 'turtle', say: ['A turtle? Where?', 'No way.'], re: ['On the log. It went under.', 'I saw it once.'] },
          { k: 'gross', t: 'algae', say: "Somebody should clean it.", re: ['The city? Ha.', 'Volunteer, then.'] }] },
  ],
  pool: [
    { id: 'water', q: [['say', "Water's actually nice {today}.", 'nice'], ['yn', 'You getting in?', 'in'], ['yn', 'Are you coming in or not?', 'in']],
      a: { nice: ["Yeah, it's not bad.|agree", 'Told you.|agree', 'Way better than yesterday.|agree', 'Still feels cold to me.|cold'], in: ['Yeah, give me a second.|yes', 'In a minute.|yes', "Nope, I'm good.|no", 'Maybe. Let me test it first.|maybe'] },
      n: [{ k: 'in', t: 'maybe', say: "It's warm, I promise.", re: ['You said that last time.', "We'll see."] },
          { k: 'in', t: 'no', say: 'Come on, get in.', re: ["I'm coming.", 'Give me a minute.', 'Not happening.'] },
          { k: 'nice', t: 'cold', say: 'You get used to it.', re: ["That's what people say about cold water.", 'Maybe in a minute.'] }] },
    { id: 'sunscreen', light: true, q: [['yn', 'You bring sunscreen?', 'have'], ['yn', 'Do you have sunscreen?', 'have'], ['yn', 'Please tell me you brought sunscreen.', 'have']],
      a: { have: ["Yeah, it's in my bag.|yes", 'I think so. Check the side pocket.|yes', 'No, I forgot it.|no', 'I ran out this morning.|no'] },
      n: [{ k: 'have', t: 'no', say: "I think I'm already burning.", re: ['Get in the shade for a bit.', 'Yeah, your shoulders are getting red.'] },
          { k: 'have', t: 'yes', say: ['Thank god. My shoulders are already red.', 'Lifesaver.'], re: ['Put a lot on.', 'Help yourself.'] }] },
    { id: 'snacks', q: [['yn', 'Snack bar open?', 'open'], ['when', 'When does the snack bar close?', 'close'], ['say', 'I want a slushie so bad.', 'slushie']],
      a: { open: ["Line's huge.|open", 'Yeah, just opened.|open', 'Closed for lunch, I think.|closed'], close: ['Five.', 'Like four?|rq', 'No idea.'], slushie: ['Get me one.|want', 'Blue one.|want', 'Brain freeze incoming.|want'] },
      n: [{ k: 'slushie open', t: 'want open', say: 'Cherry or blue?', re: ['Blue. Obviously.', 'Cherry.', 'Both.'] },
          { k: 'open', t: 'closed', say: ['For lunch? They SELL lunch.', 'Of course it is.'], re: ['I know.', 'Twenty minutes, they said.'] }],
      back: ['...still want that slushie.|want'] },
    { id: 'lifeguard', q: [['yn', 'Is the lifeguard even awake?', 'awake'], ['say', "Lifeguard's been on his phone all day.", 'phone']],
      a: { awake: ['Barely.', 'He blew the whistle earlier.', "He's wearing sunglasses, who knows."], phone: ['Ha. Yeah.', 'Not our problem.', 'Must be nice.'] } },
  ],
  office: [
    { id: 'meeting', q: [['when', 'When is the meeting again?', 'when'], ['yn', 'You going to the meeting?', 'going'], ['yn', "Are you sitting in on the three o'clock?", 'going']],
      a: { when: ['Three.|known', 'They pushed it to four.|known', "I think it's at three.|known", 'Tomorrow morning, unless they changed it again.|known'], going: ['Yeah, I have to.|yes', 'Unfortunately.|yes', "No, I'm skipping it.|no", 'I think so.|yes'] },
      n: [{ k: '*', t: 'known yes', say: "What's it even about?", re: ['The new system.', 'Budget stuff, I think.', 'No idea. I stopped reading after the first email.'] },
          { k: 'going', t: 'no', say: ["Lucky. How'd you get out of it?", 'You can just skip it?'], re: ['I said I had a conflict.', "Nobody's checking."] }] },
    { id: 'printer', q: [['yn', 'Is the printer working?', 'working'], ['say', "Printer's broken again.", 'broken']],
      a: { working: ['If you kick it.|no', 'Out of toner.|no', 'Try the one upstairs.|no', 'It was never fixed.|no'], broken: ['Shocking.|dry', 'Did you call IT?|ask', 'It hates you specifically.|dry'] },
      n: [{ k: '*', t: 'no dry', say: 'I need this printed by noon.', re: ['Email it.', 'Good luck.', 'Upstairs one works.'] },
          { k: 'broken', t: 'ask', say: ['Twice. They said Tuesday.', "Ticket's open. Again."], re: ['So never.', 'Classic IT.'] }] },
    { id: 'coffee', q: [['yn', 'Coffee?', 'want'], ['yn', 'Want me to grab you coffee?', 'want'], ['say', 'I need coffee before I talk to anyone.', 'need']],
      a: { want: ['Please.|yes', 'Yeah, thanks.|yes', "I'm good.|no", 'Only if the pot is fresh.|yes'], need: ['Same.|same', "You're already talking to me.|tease", "There's a fresh pot in the kitchen.|pot", 'That makes two of us.|same'] },
      n: [{ k: 'want', t: 'yes', say: "The machine's out again, though.", re: ['Of course it is.', 'Try the kitchen upstairs.', "Then I'm going home."] },
          { k: 'need', t: 'pot', say: ['Bless you.', 'Finally, good news.'], re: ["Hurry before it's gone."] },
          { k: 'need', t: 'tease', say: "This doesn't count.", re: ["Sure it doesn't."] }],
      back: ['...I still need that coffee.'] },
    { id: 'fridge', q: [['say', 'Someone ate my yogurt again.', 'ate'], ['who', 'Who keeps taking food from the fridge?', 'who']],
      a: { ate: ['Not me.|deny', 'Label it.|tip', 'Probably Kevin.|kevin'], who: ['Kevin.|kevin', 'Not me, I swear.|deny', "Nobody knows. It's a mystery.|unknown"] },
      n: [{ k: 'ate', t: 'tip', say: 'It had my name on it.', re: ['Then it was definitely Kevin.', 'Huh.', 'Start hiding it.'] },
          { k: '*', t: 'kevin', say: ['I knew it was Kevin.', "It's always Kevin."], re: ['Everyone knows. Nobody says anything.', 'Say something to him.'] }] },
    { id: 'friday', q: [['yn', 'Is it Friday yet?', 'fri'], ['say', 'This week is taking forever.', 'long']],
      a: { fri: ['Not even close.', 'I wish.', 'Feels like it should be.', "Don't remind me."], long: ['Seriously.', 'I know.', 'Every day feels like Monday here.', 'It really is.'] } },
  ],
  checker: [
    { id: 'who', q: [['who', 'Who even built this place?', 'who'], ['yn', 'Is this an art thing?', 'art']],
      a: { who: ['Some rich guy.', 'No idea.', 'Same people who did the big sculpture downtown.'], art: ['Has to be.', 'I think so.', 'Looks like a game show.'] } },
    { id: 'photo', q: [['yn', 'Take my picture by the king?', 'pic'], ['yn', 'Get a photo with the horse?', 'pic']],
      a: { pic: ['Hold still.|yes', 'One sec.|yes', 'Sure.|yes'] },
      n: [{ k: 'pic', t: 'yes', by: 'b', say: ['Your eyes were closed. Again.', 'Okay, one more. You blinked.'], re: ['Seriously?|rq', 'Again?|rq'] }] },
  ],
  crew: [
    { id: 'suit', q: [['yn', 'Suit pressure look okay?', 'press'], ['yn', 'Everything green on my suit?', 'press'], ['how', "How's your oxygen?", 'o2']],
      a: { press: ['Yeah, all green.|ok', 'Looks good from here.|ok', "Pressure's a little low. Keep an eye on it.|low", "Hold on... yeah, you're good.|ok"], o2: ['Seventy percent.|ok', 'Fine for now.|ok', "Getting low. I'll head back soon.|low", 'About half.|ok'] },
      n: [{ k: '*', t: 'ok', say: 'Base wants us back in an hour.', re: ['Copy.', 'That gives us time.', "Tell them we're wrapping up."] },
          { k: '*', t: 'low', say: ["Don't push it.", 'Head back if it drops more.'], re: ['Copy that.', "I know. I'm watching it."] }] },
    { id: 'samples', q: [['how', 'How many samples left?', 'left'], ['yn', 'We done sampling yet?', 'left']],
      a: { left: ['Six more.|more', 'Two. Then lunch.|few', 'Lost count.|unknown', 'Nearly.|few', 'Not even close.|more', 'Base says four more.|more'] },
      n: [{ k: '*', t: 'more', say: 'My back is killing me.', re: ['Same. Keep going.', 'Lift with your legs.'] },
          { k: '*', t: 'unknown', say: ['Check the log.', 'You lost count?'], re: ['The tablet froze.', 'Okay, okay. Checking.'] }],
      back: ['...base still wants those samples.'] },
    { id: 'home', q: [['yn', 'Talked to your family yet?', 'talked'], ['when', "When's the next call home?", 'when']],
      a: { talked: ['Yeah, last night.|yes', "Not yet. Signal's been awful.|no", 'A few days ago.|yes', 'Tried, but the call dropped.|no'], when: ['Thursday.', 'Tonight, hopefully.', 'Whenever the dish starts working again.'] },
      n: [{ k: 'talked', t: 'yes', say: 'How are they doing?', re: ['Good. They miss me.', "Fine. My kid's learning to ride a bike."] },
          { k: 'talked', t: 'no', say: "They'll understand.", re: ['I hope so.', 'Yeah.'] }] },
  ],
  station: [
    { id: 'shift', q: [['when', 'When are you off?', 'off'], ['how', 'How long do you have left?', 'left']],
      a: { off: ['Midnight.|later', 'In about twenty minutes.|soon', "I was supposed to be off an hour ago. I'm covering.|late", 'Not until morning.|later'], left: ['About twenty minutes.|soon', 'A couple hours.|later', 'Too long.|later', "I'm on a double, so don't ask.|late"] },
      n: [{ k: '*', t: 'soon later', say: 'Want to swap Thursday?', re: ['Sure.', 'Only if you take Saturday.', 'No way.'] },
          { k: '*', t: 'late', say: ["That's rough.", 'You need to say no sometimes.'], re: ['Tell that to my boss.', 'I know.'] }] },
    { id: 'maint', q: [['yn', 'Did maintenance ever fix that panel?', 'fixed'], ['say', "That panel's sparking again.", 'spark']],
      a: { fixed: ['Nope.|no', 'They said Tuesday.|no', 'Which panel?|ask'], spark: ["Don't touch it.", 'Log it.', "It's been doing that all week."] },
      n: [{ k: 'fixed', t: 'ask', say: 'The one by the lab door.', re: ['Oh, that one. No.', 'Still broken.', "I'll put in a ticket."] }] },
    { id: 'food', q: [['what', "What's for dinner?", 'what'], ['yn', "Please tell me it's not the paste again.", 'paste']],
      a: { what: ['Paste.|paste', 'Rehydrated something.', "Mike's making curry. Allegedly.|curry"], paste: ["It's the paste.|paste", 'Better. Rehydrated pasta.', 'Worse.'] },
      n: [{ k: '*', t: 'paste', say: ["I'm going to dream about real food.", "I can't do the paste again."], re: ['Three more weeks.', "It's not that bad. It's bad. But not that bad."] },
          { k: 'what', t: 'curry', say: 'Allegedly?', re: ['Last time it was supposed to be curry. It was soup.'] }] },
    { id: 'air', q: [['yn', 'Did you check the scrubbers?', 'checked'], ['say', 'Air smells weird today.#weird', 'smell']],
      a: { checked: ['Twice.', 'Doing it now.', "That's not my job."], smell: ["That's Mike's lunch.", 'It always smells weird.', 'Log it.'] } },
  ],
  bunker: [
    { id: 'shift', q: [['who', "Who's on after us?", 'who'], ['say', 'Shift change in ten.', 'change']],
      a: { who: ['Davis. Ugh.|davis', "Nobody, we're on doubles.|double", 'The new guy.|new'], change: ['Finally.', 'Twenty, actually.', "Don't get excited."] },
      n: [{ k: 'who', t: 'davis', say: 'He never shows up on time.', re: ['Never.', 'Last time he was forty minutes late.'] },
          { k: 'who', t: 'double', say: ["You're joking.", 'Again?'], re: ['Wish I was.', 'Nope. Doubles all week.'] },
          { k: 'who', t: 'new', say: 'Does he even know where the coffee is?', re: ['He will by tomorrow.', 'Nope.'] }] },
    { id: 'radio', q: [['yn', 'Hear anything on the radio?', 'hear'], ['say', "Radio's been quiet.", 'quiet']],
      a: { hear: ['Static.', 'Nothing.', 'Someone humming. Weird.|weird'], quiet: ["Quiet's good.", 'Too quiet.#weird', 'Turn it up.'] },
      n: [{ k: 'hear', t: 'weird', say: 'Humming? On our channel?', re: ['Probably interference.', "That's what it sounded like."] }] },
    { id: 'cards', q: [['yn', 'Cards after shift?', 'cards'], ['say', 'You owe me from last night.', 'owe']],
      a: { cards: ['Deal.|yes', 'Not with you. You cheat.|cheat', 'Double or nothing.|yes'], owe: ["I don't owe you anything.|deny", 'Double or nothing?|ask', 'Put it on my tab.'] },
      n: [{ k: 'cards', t: 'cheat', say: 'I do not cheat.', re: ['You had five aces.', "Sure you don't."] },
          { k: 'owe', t: 'ask', say: ['Deal.', "You're on."], re: ['Bring money this time.'] },
          { k: 'owe', t: 'deny', say: 'You lost three hands in a row.', re: ['Two. And one was a misdeal.'] }] },
    { id: 'food', q: [['what', "What's for chow?", 'what'], ['yn', 'Please not the beans again.', 'beans']],
      a: { what: ['Beans.|beans', 'Mystery stew.', 'Same as yesterday.'], beans: ['Beans.|beans', 'Worse. Stew.', 'Better than nothing.'] },
      n: [{ k: '*', t: 'beans', say: ['Every day. Every single day.', "I'm going to turn into a bean."], re: ['Could be worse.', "Eat it or don't."] }] },
  ],
  club: [
    { id: 'song', q: [['say', 'I LOVE THIS SONG!', 'love'], ['who', "WHO'S DJING?", 'dj'], ['say', 'THIS SONG!', 'love']],
      a: { love: ['WHAT?|what', 'SAME!', "IT'S THE SAME SONG!", 'YEAH!'], dj: ['NO IDEA!', 'SOME GUY!', "HE'S GOOD!"] },
      n: [{ k: 'love', t: 'what', say: 'I SAID I LOVE THIS SONG!', re: ['OH! SAME!', 'YEAH!'] }] },
    { id: 'drink', q: [['yn', 'ANOTHER DRINK?', 'drink'], ['yn', 'YOU WANT ANYTHING?', 'drink'], ['say', 'I NEED WATER.', 'water']],
      a: { drink: ['YES!|yes', "I'M GOOD!|no", 'WATER!|water', "YOU'RE BUYING!|yes"], water: ['BAR!', 'OVER THERE!', 'GET ME ONE!'] },
      n: [{ k: 'drink', t: 'yes', say: 'WHAT DO YOU WANT?', re: ['SURPRISE ME!', 'THE PINK ONE!', 'WATER!'] }],
      back: ['...I really need that drink now.'] },
    { id: 'jess', q: [['where', "WHERE'S JESS?", 'where'], ['yn', 'HAVE YOU SEEN JESS?', 'where']],
      a: { where: ['BAR!|bar', 'BATHROOM LINE!', 'DANCING!', 'WHO?|who', 'NO!', 'SHE LEFT!|left'] },
      n: [{ k: '*', t: 'bar', say: 'WHICH BAR?', re: ['THERE IS ONE BAR!', 'THE BAR! THE ONLY BAR!'] },
          { k: '*', t: 'who', say: ['JESS! JESS!', 'YOUR FRIEND JESS!'], re: ['OH! NO IDEA!', 'WHAT?|rq'] },
          { k: '*', t: 'left', say: 'WITHOUT US?!', re: ['TYPICAL JESS!', 'YEP!'] }] },
    { id: 'loud', q: [['say', "IT'S SO LOUD!", 'loud'], ['yn', 'OUTSIDE FOR A SEC?', 'out']],
      a: { loud: ['WHAT?|rq', "IT'S A CLUB!", 'I KNOW!'], out: ['ONE MORE SONG!', 'YES!', 'NO!'] } },
    { id: 'ride', q: [['how', 'HOW ARE WE GETTING HOME?', 'ride'], ['who', "WHO'S DRIVING?", 'driver']],
      a: { ride: ['CAB!|plan', 'ASK ME LATER!|none', 'WALKING, APPARENTLY!|plan'], driver: ['NOT ME!|none', "YOU ARE!|you", 'NOBODY! CAB!|plan'] },
      n: [{ k: 'ride driver', t: 'none', say: 'SOMEONE HAS TO!', re: ['FINE! CAB!', 'LATER!'] }, { k: 'driver', t: 'you', say: "I'VE HAD THREE DRINKS!", re: ['CAB, THEN!', 'OKAY, CAB!'] }],
      back: ['...seriously, how are we getting home?'] },
  ],
};
/* how different people answer, per kind of question. Deliberately broad (they replace many specific answers), and tagged
   unsure, so a follow-up that needs a real yes or no never comes after a shrug. */
const PERSONA_ANS = {
  rude: { when: ["I don't know. Check.|unsure", 'Why are you asking me?|unsure'], where: ['No idea.|unsure', 'Go look.|unsure'], yn: ['How would I know?|unsure', 'Probably. Whatever.|unsure'],
    what: ['No idea.|unsure', 'Ask somebody else.|unsure'], how: ["I don't know.|unsure", 'Why do you care?|unsure'], who: ['Not me.|unsure', 'No clue.|unsure'], say: ['Okay?|unsure', 'And?|unsure', 'Good to know.|unsure'] },
  quiet: { when: ['Not sure.|unsure', "I don't know.|unsure"], where: ['Not sure.|unsure', 'Over there, I think.|unsure'], yn: ['Maybe.|unsure'],
    what: ["I don't know.|unsure", 'Not sure.|unsure'], how: ['Not sure.|unsure', "I don't know.|unsure"], who: ['No idea.|unsure', 'Not sure.|unsure'], say: ['Yeah.|unsure', 'Mm.|unsure', 'I know.|unsure'] },
  distracted: { yn: ['Sorry, what? Uh... maybe.|unsure'], when: ["Sorry, what? I'm not sure.|unsure", "Uh... I don't remember.|unsure"], where: ["Wait, what? I don't know.|unsure"],
    what: ["Huh? Sorry, I wasn't listening.|unsure", "I don't know.|unsure"], how: ['Sorry, what was the question?|unsure', 'Uh... not sure.|unsure'], who: ['Who? Sorry, I missed that.|unsure', 'No idea.|unsure'], say: ['Sorry, I was looking at something.|unsure', 'Huh? Yeah.|unsure'] },
  funny: { say: ['Huge development.|unsure', 'That changes everything.|unsure', 'Tragic.|unsure'], yn: ["I'm gonna go with maybe.|unsure", 'Sure. Why not?|unsure'] }, // only where a generic joke still fits the question
};
const PERSONA_K = [['rude', .3], ['quiet', .4], ['distracted', .22], ['funny', .15]];
const SWITCH = { q: ['Anyway.', 'Oh, random question.', 'Unrelated, but—', 'Anyway, um.', 'Hey, so.'], say: ['Anyway.', 'Oh, that reminds me.', 'Anyway, um.', 'Oh, totally different thing.'] }; // what fits before a question isn't what fits before a statement
/* coming back to a talk the snake cut off: the one who was talking picks it up, or nobody can remember */
const CONVO_RESUME = ['Anyway, what I was saying—', 'So. Anyway.', 'Okay. Um. Anyway.', 'Like I was saying, before... that.'];
const CONVO_LOST = ['I completely forgot what I was talking about.', 'I had a point. It\'s gone.', 'Never mind. Doesn\'t matter now.', "...I don't even remember what we were talking about."];
const CONVO_LOST_RE = ['Yeah. Me neither.', 'Honestly? Same.', "Can't blame you.", "Doesn't matter."];
/* things people say while they're doing something */
const DOING = {
  dog: ['Slow down, buddy.', 'Leave it. LEAVE IT.', 'Good boy.', 'No, we are not chasing that.', 'Heel. Heel! Ugh.'],
  dance: ['WOO!', 'This part!', 'I love this part!', "Don't stop!", 'One more song!'],
  flashlight: ['Batteries are dying.', 'Can barely see a thing.', 'Hold on, let me point this over there.'],
  winter: ["It's freezing.", 'My fingers are numb.', "Should've worn gloves.", 'I can see my breath.'],
  autumn: ['Leaves everywhere.', 'Getting dark so early now.', 'Smells like bonfires.'],
  spring: ["Everything's blooming.", 'My allergies are killing me.', 'Finally warm out.'],
  summer: ["It's so hot.", "I'm melting.", 'Need some shade.'],
  night: ["It's so dark out here.", "Should've brought a flashlight.", "Streetlight's out again."],
};
/* ---- weather small talk: picked by season, and by how cold it actually is right now (time of day counts) ---- */
const WEATHER_TALK = {
  freezing: [ // winter, night or early morning
    { id: 'wx-freeze', q: [['say', "It's freezing. I can't feel my fingers.", 'cold'], ['yn', 'Is it just me or is it colder than yesterday?', 'colder'], ['say', 'My breath is literally smoking.', 'cold']],
      a: { cold: ['Same. My ears are gone.|same', "Should've worn gloves.|scold", 'Stop complaining, walk faster.|tease', "At least it's not windy.|same"], colder: ['Way colder.|yes', "It's just you.|no", 'They said minus eight tonight.|yes', 'Feels like it.|yes'] },
      n: [{ k: '*', t: 'same yes', say: "I'm going home after this, I swear.", re: ['You say that every time.', 'Take me with you.'] },
          { k: '*', t: 'tease scold no', say: "The pond's probably frozen solid.", re: ["Don't even think about walking on it.", 'Good. Skating.', 'Ducks must hate this.'] }],
      back: ['Still freezing, by the way.'] },
    { id: 'wx-ice', q: [['say', "Watch it, the ground's all ice.", 'ice'], ['yn', 'Did you slip earlier? I heard something.', 'slip']],
      a: { ice: ['I almost ate it back there.', 'Thanks, mom.', 'They never salt this bit.'], slip: ['Maybe.|yes', "Don't tell anyone.|yes", 'That was my dignity hitting the floor.|yes'] },
      n: [{ k: 'slip', t: 'yes', say: ['Are you okay?', 'Did you hurt yourself?'], re: ['Only my pride.', "I'll have a bruise tomorrow."] }] }],
  winter: [
    { id: 'wx-snow', q: [['yn', "Think it's going to snow again?", 'more'], ['say', 'I love it when it snows like this.', 'love'], ['when', "When's this snow supposed to melt?", 'melt']],
      a: { more: ['Looks like it.|yes', 'Hope not.|no', 'The forecast said tonight.|yes', 'More? Seriously?|no rq'], love: ["It's pretty for about a day.", 'Wait till it turns to slush.', 'You would.'], melt: ['Next week, maybe.', 'March.', 'Never, apparently.'] },
      n: [{ k: 'love more', say: 'We should build a snowman.', re: ["We're adults.", "I'm in.", 'Last one got kicked over.'] },
          { k: '*', say: 'Somebody made snow angels over there.', re: ['Probably kids.', 'That was me.', 'Cute.'] }],
      back: ['Still snowing?'] }],
  autumn: [
    { id: 'wx-leaves', q: [['say', 'Leaves are everywhere already.', 'leaves'], ['yn', 'Is it getting dark earlier or is it just me?', 'dark']],
      a: { leaves: ['Best time of year.|like', "Somebody's got to rake that.|chore", 'Love the crunch, though.|like'], dark: ['Clocks change soon.|yes', "It's autumn, genius.|yes", 'Way earlier.|yes'] },
      n: [{ k: 'dark', t: 'yes', say: 'I need a proper coat.', re: ['Told you.', 'Borrow mine.', 'Just layer up.'] },
          { k: 'leaves', t: 'like chore', say: 'Smells like rain.', re: ['Great.', 'Smells like bonfires to me.', 'I like it.'] }] },
    { id: 'wx-chilly', q: [['say', "It's getting chilly.", 'chilly'], ['yn', 'Did you bring a jacket?', 'jacket']],
      a: { chilly: ['Sweater weather.', 'Yeah, it turned fast.', "I'm fine. I'm not fine."], jacket: ['No, and I regret it.|no', 'Obviously.|yes', 'It was warm this morning!|no'] },
      n: [{ k: 'jacket', t: 'no', say: 'Want mine?', re: ['Yes. Please.', "No, I'm being stubborn."] }] }],
  spring: [
    { id: 'wx-spring', q: [['say', 'Finally a bit of sun.', 'sun'], ['yn', 'Is it going to rain again today?', 'rain']],
      a: { sun: ['About time.', "Don't jinx it.", 'My allergies disagree.|allergy'], rain: ["Probably. It's spring.|yes", 'Looks clear.|no', 'Bring an umbrella.|yes'] },
      n: [{ k: '*', t: 'allergy no', say: "Everything's blooming.", re: ["I'm sneezing just looking at it.", "It's nice.", 'Bees, though.'] }] }],
  summer: [
    { id: 'wx-heat', q: [['say', "It's way too hot today.", 'hot'], ['yn', 'Did you put sunscreen on?', 'sun'], ['say', "I'm melting.", 'hot']],
      a: { hot: ["I've sweated through my shirt.", "At least it's not raining.", 'Find some shade, then.'], sun: ['Forgot.|no', 'Twice.|yes', "I tan, I don't burn.|no"] },
      n: [{ k: 'hot', say: 'I could kill for an ice cream.', re: ['Same.', 'The van went past earlier.', 'You and every kid here.'] },
          { k: 'sun', t: 'no', say: "You're going to regret that.", re: ['Probably.', 'I never learn.'] }] }],
  warmNight: [
    { id: 'wx-night', q: [['say', 'Nice night, at least.', 'nice'], ['yn', 'Still warm, huh?', 'warm']],
      a: { nice: ["Yeah, it's actually pleasant.", 'Too quiet, though.', 'Bit too dark round here.'], warm: ['Barely cooled down.', 'Perfect weather.', 'Mosquitoes love it.'] } }],
};
function weatherTalk() { // which of the above fits right now: season, then how cold this hour actually is
  const m = MAPS[mapIdx]; if (!m || m.indoor || m.space || !season) return [];
  const h = (typeof tod === 'number' ? tod : 12) % 24, night = h < 6.5 || h > 20, id = season.id;
  if (id === 'winter') return [...WEATHER_TALK.winter, ...(night || h < 9 ? WEATHER_TALK.freezing : [])];
  if (id === 'autumn') return WEATHER_TALK.autumn.concat(night ? WEATHER_TALK.freezing.slice(0, 1) : []);
  if (id === 'summer') return night ? WEATHER_TALK.warmNight : WEATHER_TALK.summer;
  return WEATHER_TALK.spring;
}
/* ---- compile: tags parsed once, "?" answers marked as questions, every topic checked for follow-ups that can never fire ---- */
const parseTagged = s => { const [text, tags] = s.split('|'); const t = tags ? tags.split(' ') : []; if (/\?$/.test(text) && !t.includes('ask') && !t.includes('rq')) t.push('ask'); return { text, tags: t }; }; // rq: a rhetorical or tentative question ("Already?", "Maybe noon?") that needs no answer
const splitKeys = s => s ? s.split(' ') : null;
function compileTopic(tp) {
  if (tp.compiled) return tp; tp.compiled = true;
  tp.q = tp.q.map(([type, text, key]) => ({ type, text, key: key || type }));
  const A = {}; for (const k in tp.a || {}) A[k] = tp.a[k].map(parseTagged); tp.A = A;
  const node = n => ({ k: n.k === '*' || !n.k ? null : splitKeys(n.k), t: splitKeys(n.t), by: n.by, say: [].concat(n.say), re: (n.re || []).map(parseTagged), then: (n.then || []).map(node) });
  tp.N = (tp.n || []).map(node);
  tp.B = (tp.back || []).map(s => { const [text, req] = s.split('|'); return { text, req }; });
  return tp;
}
for (const k in TALK) TALK[k].forEach(compileTopic);
for (const k in WEATHER_TALK) WEATHER_TALK[k].forEach(compileTopic);
for (const k in PERSONA_ANS) for (const t in PERSONA_ANS[k]) PERSONA_ANS[k][t] = PERSONA_ANS[k][t].map(parseTagged);
