/* =========================================================
   CONVERSATIONS. Every opener has a type, and answers are grouped by that type, so a reply always fits what was
   actually said:  yn = yes/no question, when, where, what, how, who, say = a statement (gets a reaction).
   n = follow-up exchanges: [what the first person says next, [ways the other one answers it]]. Any of them can be
   picked, in any order, so a talk can run for a while or stop after one line.
   back = how someone brings the topic up again later, once the danger has passed.
   "#tag" opens a thread something later can close ("I swear something's weird tonight.#weird" -> "SEE? I TOLD YOU.").
   ========================================================= */
const TALK = {
  generic: [
    { id: 'phone', q: [['say', "My phone's almost dead."], ['say', "Ugh, my battery's at like five percent."], ['yn', 'You got a charger on you?'], ['yn', 'Can I borrow your charger later?']],
      a: { say: ['Mine too.', "Should've charged it last night.", "There's a charger in the car.", 'Put it on low power mode.', 'Classic.'], yn: ["In the car, yeah.", 'Nope, sorry.', "Not one that fits yours.", 'Yeah, remind me later.', "Mine's broken, so no."] },
      n: [["I need it for the bus times.", ["Just ask someone.", "The bus is late anyway.", "I know them by heart. Kind of."]], ["Who are you texting anyway?", ["Nobody.", "My sister.", "None of your business."]]] },
    { id: 'tired', q: [['say', "I'm so tired."], ['yn', 'Did you sleep at all last night?'], ['say', "I could fall asleep standing up."], ['how', 'How are you even awake right now?']],
      a: { say: ['Same.', 'Go to bed earlier then.', 'Coffee. Seriously.', 'You say that every day.', 'Long week?'], yn: ['Like four hours.', 'Not really, no.', 'Barely.', 'Yeah, actually. First time in ages.'], how: ['Spite.', 'Three coffees.', 'I am not awake.', 'Honestly? No idea.'] },
      n: [['The neighbors were up till two again.', ['Call someone about it.', "That's so annoying.", 'Doing what?']], ["I'm going to bed the second I get home.", ['Same.', "You won't.", "No you're not."]]] },
    { id: 'time', q: [['what', 'What time is it?'], ['what', 'You got the time?'], ['yn', 'Is it four yet?']],
      a: { what: ['Almost four.', 'Quarter past three.', 'No idea, my phone died.', 'Like... ten to?', 'Late.'], yn: ['Just about.', 'Not yet.', 'Way past.', 'No clue. Maybe?'] },
      n: [["We're gonna be late.", ['We always are.', "Then walk faster.", "No we're not. Probably."]]] },
    { id: 'hungry', q: [['say', "I'm starving."], ['yn', 'You hungry?'], ['what', 'What do you want to eat later?']],
      a: { say: ['We just ate.', 'Could eat.', 'You\'re always starving.', "There's a granola bar in my bag."], yn: ['Always.', 'Not really.', 'Kinda, yeah.', "I could eat."], what: ['Anything that isn\'t salad.', 'Burgers?', "I don't care. You pick.", 'Something cheap.'] },
      n: [['Burgers?', ['Again?', 'Fine by me.', "I'm trying not to."]], ['You pick this time.', ["You'll just say no to whatever I pick.", 'Fine. Tacos.', 'Ugh. Okay.']]], back: ["...I'm still hungry. Is that bad?"] },
    { id: 'weather', q: [['yn', 'Think it\'s gonna rain?'], ['say', 'Supposed to storm later.'], ['say', "It's colder than I thought."]],
      a: { yn: ['Hope not.', 'Probably.', 'Didn\'t check.', 'Sky says yes.'], say: ['Great.', "They said that yesterday too.", 'Good thing I brought a jacket.', "That's what I heard."] },
      n: [['I didn\'t bring a jacket.', ['Should\'ve.', 'You can have mine. Kidding.', "That's on you."]]] },
    { id: 'weekend', q: [['what', 'What are you doing this weekend?'], ['yn', 'You doing anything this weekend?'], ['say', 'I need this weekend so bad.']],
      a: { what: ['Sleeping.', 'My cousin\'s wedding.', 'Nothing. Thank god.', "Moving. Don't ask."], yn: ['Nope.', 'Family stuff.', 'Maybe. Depends.', 'Working, unfortunately.'], say: ['Same.', 'Two more days.', "Don't jinx it.", 'Don\'t we all.'] },
      n: [['Want to do something Saturday?', ['Sure, what?', "Can't. Sorry.", 'Maybe. Text me.']]] },
    { id: 'weird', q: [['say', "I swear something's weird tonight.#weird"], ['say', 'Does it feel weird out here or is that just me?#weird'], ['say', 'Got a bad feeling about today.#weird']],
      a: { say: ["It's just you.", "You always say that.", "Yeah, actually. A little.", "Relax.", "What kind of weird?"] },
      n: [['I dunno. Too quiet.', ["You're being paranoid.", 'Yeah, it is quiet.', "Don't say that."]]] },
  ],
  field: [
    { id: 'lost', q: [['yn', 'Are we lost?'], ['where', "Where's the car again?"], ['where', 'Which way is the road?']],
      a: { yn: ['No. Maybe.', "We're not lost, we're exploring.", 'A little, yeah.', "I know exactly where we are. Ish."], where: ['Past the fence.', 'That way. I think.', 'By the gate.', 'No idea, honestly.'] },
      n: [['You said that an hour ago.', ['And I was right then too.', "Then you lead.", "Okay, fine, I don't know."]], ['My feet are killing me.', ['Almost there.', 'Should\'ve worn real shoes.', 'Mine too.']]], back: ['So... which way is the car?'] },
    { id: 'deer', q: [['yn', 'Seen any deer yet?'], ['say', 'There were deer here last time.']],
      a: { yn: ['One, by the trees.', 'Not yet.', "You're too loud for deer.", 'Something big ran off earlier.'], say: ['Maybe they moved.', 'Shh, then.', 'At dusk, probably.'] },
      n: [['They\'re usually out around sunset.', ['Then we wait.', 'We\'ll be gone by then.', 'Cool.']]] },
    { id: 'stars', q: [['say', 'You can actually see stars out here.'], ['yn', 'Is that a planet? The bright one?']],
      a: { say: ['No city lights.', 'Yeah. It\'s nice.', 'Kind of makes you feel small.'], yn: ["That's a plane.", 'Venus, I think.', 'No idea. Looks like a plane.'] },
      n: [["It's blinking.", ['Then it\'s a plane.', 'Okay, plane.', "Satellites blink too. I think."]]] },
    { id: 'fence', q: [['yn', 'Are we even allowed past that fence?'], ['say', 'I think this is private land.']],
      a: { yn: ['Probably not.', "Nobody's gonna check.", 'There was a sign.', "Didn't see a sign."], say: ['So?', "Then let's not get caught.", "It's a field. Who cares."] },
      n: [['What did the sign say?', ["Didn't read it.", "No trespassing, I think.", 'Something about dogs.']]] },
  ],
  meadow: [
    { id: 'lake', q: [['yn', 'Want to go in the lake?'], ['yn', 'Is the lake cold?'], ['say', "Lake looks nice today."]],
      a: { yn: ['Freezing.', 'Later, maybe.', 'Only up to my knees.', 'Not with the leeches.'], say: ['It does.', "Still not going in.", 'Bet it\'s cold.'] },
      n: [['Wait, there are leeches?', ['Maybe. I heard.', 'Big ones.', "Kidding. Probably."]], ['Race you to the dock.', ['No.', 'You\'ll lose.', 'Give me a minute.']]] },
    { id: 'bugs', q: [['say', 'I should\'ve brought bug spray.'], ['say', 'Something keeps biting me.'], ['yn', 'You got bug spray?']],
      a: { say: ['Told you.', "It's the lake.", "Don't scratch it.", 'They like you more than me.'], yn: ['In my bag. Somewhere.', 'Ran out.', 'Yep. Hold still.', 'Nope. Sorry.'] },
      n: [['You did not tell me.', ['In the car. Twice.', 'I definitely did.', 'Okay, maybe I thought it.']]] },
    { id: 'fire', q: [['say', "Fire's getting low."], ['yn', 'Should we put more wood on?'], ['who', 'Whose turn is it to get wood?']],
      a: { say: ['I\'ll get some.', 'Let it go out.', 'In a sec.'], yn: ['Yeah, go for it.', 'Wood\'s all damp.', 'Let it die, I\'m tired.'], who: ['Yours.', "Not mine, I went last time.", "Nobody's. Let it go out."] },
      n: [['There\'s dry stuff under the tarp.', ['Then you get it.', 'Smart.', 'Okay, fine, I\'ll go.']]] },
    { id: 'trail', q: [['yn', 'Does this trail loop back?'], ['how', 'How much longer is this trail?'], ['where', 'Where does this trail come out?']],
      a: { yn: ['Eventually.', "It's supposed to.", 'No idea, I\'m following you.'], how: ['Mile? Maybe two.', "Not long.", 'Longer than you want.'], where: ['By the car park.', 'Back at the tents, I think.', 'No idea.'] },
      n: [["The map said it loops.", ["The map's from 2009.", 'Then it loops.', 'Maps lie.']]], back: ['So does this trail loop back or not?'] },
    { id: 'frogs', q: [['say', 'The frogs are so loud tonight.'], ['yn', 'Hear the frogs?']],
      a: { say: ['Means rain, I think.', 'I like it.', "I can't sleep with that.", 'It\'s mating season or something.'], yn: ['Hard not to.', 'Yeah, it\'s nice.', 'Is that a frog? Sounded like a duck.'] } },
  ],
  town: [
    { id: 'pizza', q: [['when', 'When does that pizza place open?'], ['when', 'You know what time the pizza shop opens?'], ['yn', 'Is the pizza place open yet?'], ['yn', 'I kinda want pizza. Think they\'re open?']],
      a: { when: ['Eleven, I think.', 'No idea, honestly.', 'Didn\'t it open at ten?', 'Pretty sure it\'s closed today.', "Like noon? Don't quote me."], yn: ["Probably. It's almost noon.", 'Doubt it.', 'Pretty sure it\'s closed today.', 'Check your phone.', 'They were open when I walked past.'] },
      n: [['You want to get some after this?', ['I could eat.', 'Not that place.', 'If you\'re buying.']], ['Their garlic knots are amazing.', ['Overrated.', 'True.', 'They gave me food poisoning once.']]], back: ['So... still want pizza?'] },
    { id: 'traffic', q: [['say', "Traffic's been awful all day."], ['how', 'How long did it take you to get here?'], ['yn', 'Did you drive here?']],
      a: { say: ["It's the roadwork.", 'Every day.', 'Should\'ve walked.', 'Tell me about it.'], how: ['Forty minutes.', 'Way too long.', 'Ten. I walked.'], yn: ['Took the bus.', 'Yeah, parked three blocks away.', 'Walked.'] },
      n: [['They\'ve been digging up that road for months.', ['Same hole, too.', 'Never ends.', 'I think they lost something.']]] },
    { id: 'store', q: [['yn', 'Corner store still open?'], ['what', 'Need anything from the store?'], ['when', 'When does the corner store close?']],
      a: { yn: ['Till ten.', 'Should be.', 'It was earlier.'], what: ['Milk, maybe.', 'Chips.', "I'm good, thanks.", 'Batteries, actually.'], when: ['Ten.', 'Late. Eleven?', 'They close whenever the guy feels like it.'] },
      n: [['Get me something sweet.', ['Like what?', "You're not my boss.", 'Fine.']]], back: ['...we still need milk.'] },
    { id: 'alley', q: [['yn', 'You still cut through that alley?'], ['say', "Don't cut through the alley tonight."]],
      a: { yn: ['Only when I\'m late.', "It's faster.", 'Not after dark.'], say: ['Why not?', "It's fine.", 'Okay, okay.'] },
      n: [["It's gross back there.", ['It\'s two minutes faster.', 'Fair.', 'Rats don\'t bother me.']]] },
    { id: 'rent', q: [['yn', 'Did your rent go up too?'], ['say', 'Landlord raised the rent again.']],
      a: { yn: ["Don't. Don't start.", 'Of course it did.', 'Mine\'s locked in till spring.'], say: ['Again?', "That's insane.", 'Move in with me. Kidding.'] },
      n: [['I might have to move.', ['Where?', "Don't, I'll miss you.", 'Everywhere\'s the same.']]] },
  ],
  maze: [
    { id: 'way', q: [['yn', 'Did we already go this way?'], ['where', 'Which way is out?'], ['say', 'I swear we passed this hedge.']],
      a: { yn: ['Twice.', 'No? Maybe.', 'Every hedge looks the same.'], where: ['Left. I think.', 'Right. Definitely right. Maybe.', 'No idea.'], say: ['They all look the same.', 'We did.', "It's a maze. That's the point."] },
      n: [['You said that last time.', ['Then you pick.', "And I'll be right eventually.", 'Fine. Left.']]], back: ['Okay, seriously, which way is out?'] },
    { id: 'center', q: [['what', "What's even in the middle?"], ['yn', 'Is there a prize in the middle or something?']],
      a: { what: ['A bench, probably.', 'Nothing. It\'s a maze.', 'A statue, I heard.'], yn: ['Bragging rights.', 'Pretty sure no.', 'A sense of accomplishment.'] } },
    { id: 'creepy', q: [['say', 'This place is creepy at night.#weird'], ['yn', 'Why did we come here after dark?']],
      a: { say: ['It\'s fine.', 'Yeah, it\'s a lot.', 'Don\'t start.'], yn: ['Tickets were cheaper.', 'It was your idea.', "Seemed fun at the time."] } },
  ],
  farm: [
    { id: 'fence', q: [['say', 'Fence by the pigs needs fixing.'], ['yn', 'Did you see the fence by the pigs?']],
      a: { say: ['Which part?', 'Again?', 'After lunch.', 'I fixed that last week. I thought.'], yn: ['The broken bit? Yeah.', 'No, what happened?', 'Saw it. Ignored it.'] },
      n: [['The corner post. It\'s leaning.', ['I\'ll get the hammer.', 'Tomorrow.', 'That post\'s been leaning for years.']], ['The pigs keep pushing on it.', ['They\'re smarter than us.', 'Then we need a new one.', 'I\'ll move the trough.']]] },
    { id: 'hens', q: [['say', 'Hens are restless today.'], ['yn', 'Hear the chickens going off?']],
      a: { say: ['Storm coming, maybe.', 'Or a fox.', "They're always restless.", "I'll check the coop."], yn: ['Since this morning.', 'Probably a fox.', "I didn't hear anything."] },
      n: [['Something\'s got them spooked.#weird', ['Probably a fox.', "I'll take a look.", "They're chickens. Everything spooks them."]]] },
    { id: 'feed', q: [['yn', 'You feed the pigs yet?'], ['yn', 'Did the cows get fed?'], ['who', 'Who fed the animals this morning?']],
      a: { yn: ['Thought you did.', 'This morning, yeah.', 'Not yet.', 'Twice, by accident.'], who: ['Me.', 'Your dad.', 'Nobody, I think.'] },
      n: [['They\'re acting starved.', ['They always act starved.', "Then I'll feed them.", 'Don\'t fall for it.']]] },
    { id: 'tractor', q: [['yn', 'Tractor still making that noise?'], ['say', 'Tractor\'s making that noise again.']],
      a: { yn: ['Worse.', 'Kicked it. It helped.', 'Haven\'t started it today.'], say: ['Kick it.', "It's always done that.", "I'll call Dave."] } },
  ],
  park: [
    { id: 'dog', q: [['say', "He's loving this."], ['yn', 'Is he always this hyper?'], ['how', 'How old is he now?']],
      a: { say: ['Look at him go.', 'He\'d chase anything.', 'Wait till he sees a squirrel.'], yn: ['Every single day.', 'Only around ducks.', 'Only outside.'], how: ['Three.', 'Almost two.', 'Seven, believe it or not.'] },
      n: [['Can I pet him?', ['Sure, he loves it.', 'He might lick you.', 'He bites. Kidding.']]] },
    { id: 'ducks', q: [['say', 'Ducks look hungry.'], ['yn', 'Did you bring bread?']],
      a: { say: ['They always look hungry.', 'Leave them alone.', 'They\'re fine.'], yn: ["You're not supposed to feed them bread.", 'Crackers.', 'Ate it on the way here.'] },
      n: [['Wait, why not bread?', ['Bad for them, apparently.', 'Something about their stomachs.', "I don't know, I read it somewhere."]]] },
    { id: 'bench', q: [['yn', 'Wanna sit for a bit?'], ['say', 'My legs are done.']],
      a: { yn: ['Sure.', 'In a sec.', 'That bench is wet.', 'If we can find a dry one.'], say: ['We walked like a mile.', 'Sit, then.', 'Same.'] } },
    { id: 'jog', q: [['yn', 'You still running every morning?'], ['how', 'How many laps did you do?']],
      a: { yn: ['Most mornings.', 'I walk now. It counts.', 'Skipped today.'], how: ['Three.', 'One and a half.', 'Don\'t ask.'] } },
  ],
  pool: [
    { id: 'water', q: [['say', "Water's actually nice today."], ['yn', 'Is it cold?'], ['yn', 'You getting in or what?']],
      a: { say: ['Liar.', 'It\'s perfect.', 'Kinda.', 'Told you.'], yn: ['Only for the first minute.', 'Freezing.', 'Not really.', 'In a sec.', 'After I dry off.', 'Nope.'] },
      n: [['Come on, get in.', ['Fine. Fine!', 'Five more minutes.', 'Not happening.']], ['Last one in buys snacks.', ["That's not fair, I'm drying off.", "Deal.", 'You\'re on.']]] },
    { id: 'sunscreen', q: [['yn', 'You bring sunscreen?'], ['yn', 'Can I use your sunscreen?'], ['yn', 'Am I burning?']],
      a: { yn: ["It's in my bag somewhere.", 'Ran out.', 'Go for it.', 'A little.', 'Very.', 'You look like a lobster.'] },
      n: [["I'm already burning.", ['Then get in the water.', 'Told you.', 'Shade. Now.']]] },
    { id: 'snacks', q: [['yn', 'Snack bar open?'], ['when', 'When does the snack bar close?'], ['say', 'I want a slushie so bad.']],
      a: { yn: ['Line\'s huge.', 'Yeah, just opened.', "Closed for lunch, I think."], when: ['Five.', 'Like four?', 'No idea.'], say: ['Get me one.', 'Blue one.', 'Brain freeze incoming.'] },
      n: [['Cherry or blue?', ['Blue. Obviously.', 'Cherry.', 'Both.']]], back: ['...still want that slushie.'] },
    { id: 'lifeguard', q: [['yn', 'Is the lifeguard even awake?'], ['say', "Lifeguard's been on his phone all day."]],
      a: { yn: ['Barely.', 'He blew the whistle earlier.', 'He\'s wearing sunglasses, who knows.'], say: ['Ha. Yeah.', 'Not our problem.', 'Must be nice.'] } },
  ],
  office: [
    { id: 'meeting', q: [['when', 'When is the meeting again?'], ['yn', 'You going to the three o\'clock?'], ['yn', 'Did they move the meeting?']],
      a: { when: ['Three.', 'Pushed to four.', 'I thought it was tomorrow.'], yn: ['Have to.', "Not if I can help it.", 'Pushed to four.', 'Is that today?'] },
      n: [['What\'s it even about?', ['Meetings, probably.', 'The new system.', "No idea. I'll nod a lot."]]] },
    { id: 'printer', q: [['yn', 'Is the printer working?'], ['say', 'Printer\'s broken again.']],
      a: { yn: ['If you kick it.', 'Out of toner.', 'Try the one upstairs.', 'It was never fixed.'], say: ['Shocking.', "Did you call IT?", 'It hates you specifically.'] },
      n: [['I need this printed by noon.', ['Email it.', 'Good luck.', 'Upstairs one works.']]] },
    { id: 'coffee', q: [['yn', 'Coffee?'], ['yn', 'Is there any coffee left?'], ['say', 'I need coffee before I talk to anyone.']],
      a: { yn: ['Please.', "Machine's out.", 'Just made a pot.', 'Not that coffee.'], say: ['Same.', 'You\'re talking to me now.', 'Pot\'s fresh.'] },
      n: [["Machine's out again.", ['Then I quit.', 'Kitchen upstairs has some.', 'Of course it is.']]], back: ['...I still need that coffee.'] },
    { id: 'fridge', q: [['say', 'Someone ate my yogurt again.'], ['who', 'Who keeps taking food from the fridge?']],
      a: { say: ['Not me.', 'Label it.', 'Probably Kevin.'], who: ['Kevin.', 'Not me, I swear.', "Nobody knows. It's a mystery."] },
      n: [['It had my name on it.', ['Then it was definitely Kevin.', 'Huh.', 'Start hiding it.']]] },
    { id: 'friday', q: [['yn', 'Is it Friday yet?'], ['say', "Can't believe it's only Tuesday."]],
      a: { yn: ["It's Wednesday.", 'Feels like it should be.', "Don't."], say: ["It's Wednesday.", 'Don\'t remind me.', 'Every day\'s Monday here.'] } },
  ],
  checker: [
    { id: 'who', q: [['who', 'Who even built this place?'], ['yn', 'Is this an art thing?']],
      a: { who: ['Some rich guy.', 'No idea.', 'Same people who did the big sculpture downtown.'], yn: ['Has to be.', 'I think so.', 'Looks like a game show.'] } },
    { id: 'photo', q: [['yn', 'Take my picture by the king?'], ['yn', 'Get a photo with the horse?']],
      a: { yn: ['Hold still.', 'One sec.', 'Your eyes were closed. Again.', 'Sure.'] } },
  ],
  crew: [
    { id: 'suit', q: [['yn', 'Suit pressure okay?'], ['yn', 'Check my seal?'], ['how', 'How\'s your oxygen?']],
      a: { yn: ['Green across the board.', 'You\'re good.', 'Hang on. Yeah. Good.', 'Little low. Watch it.'], how: ['Seventy percent.', 'Fine.', 'Getting low. I\'ll head back soon.'] },
      n: [['Base wants us back in an hour.', ['Copy.', 'Plenty of time.', "Tell them we're working on it."]]] },
    { id: 'samples', q: [['how', 'How many samples left?'], ['yn', 'We done sampling yet?']],
      a: { how: ['Six more.', 'Two. Then lunch.', 'Lost count.'], yn: ['Nearly.', 'Not even close.', 'Base says four more.'] }, back: ['...base still wants those samples.'] },
    { id: 'home', q: [['yn', 'Talked to your family yet?'], ['when', "When's the next call home?"]],
      a: { yn: ['Tonight, hopefully.', 'Signal\'s been garbage.', 'Last week.'], when: ['Thursday.', 'Tonight.', 'Whenever the dish works.'] } },
  ],
  station: [
    { id: 'shift', q: [['when', 'When does your shift end?'], ['how', 'How long left on shift?']],
      a: { when: ['Twenty minutes.', 'Midnight. Station time.', 'Ended an hour ago, I\'m covering.'], how: ['Ages.', 'Twenty minutes.', "I'm on doubles. Don't ask."] },
      n: [['Want to swap Thursday?', ['Sure.', 'Only if you take Saturday.', 'No way.']]] },
    { id: 'maint', q: [['yn', 'Did maintenance ever fix that panel?'], ['say', "That panel's sparking again."]],
      a: { yn: ['Nope.', 'They said Tuesday.', 'Which panel?'], say: ["Don't touch it.", 'Log it.', "It's been doing that all week."] },
      n: [['The one by the lab door.', ['Oh, that one. No.', 'Still broken.', "I'll put in a ticket."]]] },
    { id: 'food', q: [['what', "What's for dinner?"], ['yn', 'Please tell me it\'s not the paste again.']],
      a: { what: ['Paste.', 'Rehydrated something.', "Mike's making curry. Allegedly."], yn: ['It\'s the paste.', 'Better. Rehydrated pasta.', 'Worse.'] } },
    { id: 'air', q: [['yn', 'Did you check the scrubbers?'], ['say', 'Air smells weird today.#weird']],
      a: { yn: ['Twice.', 'Doing it now.', "That's not my job."], say: ["That's Mike's lunch.", 'It always smells weird.', 'Log it.'] } },
  ],
  bunker: [
    { id: 'shift', q: [['who', "Who's on after us?"], ['say', 'Shift change in ten.']],
      a: { who: ['Davis. Ugh.', 'Nobody, we\'re on doubles.', 'The new guy.'], say: ['Finally.', 'Twenty, actually.', "Don't get excited."] } },
    { id: 'radio', q: [['yn', 'Hear anything on the radio?'], ['say', "Radio's been quiet."]],
      a: { yn: ['Static.', 'Nothing.', 'Someone humming. Weird.'], say: ["Quiet's good.", 'Too quiet.#weird', 'Turn it up.'] } },
    { id: 'cards', q: [['yn', 'Cards after shift?'], ['say', 'You owe me from last night.']],
      a: { yn: ['Deal.', 'Not with you. You cheat.', 'Double or nothing.'], say: ["I don't owe you anything.", 'Double or nothing?', 'Put it on my tab.'] } },
    { id: 'food', q: [['what', "What's for chow?"], ['yn', 'Please not the beans again.']],
      a: { what: ['Beans.', 'Mystery stew.', 'Same as yesterday.'], yn: ['Beans.', 'Worse. Stew.', 'Better than nothing.'] } },
  ],
  club: [
    { id: 'song', q: [['say', 'I LOVE THIS SONG!'], ['who', "WHO'S DJING?"], ['say', 'THIS SONG!']],
      a: { say: ['WHAT?', 'SAME!', "IT'S THE SAME SONG!", 'YEAH!'], who: ['NO IDEA!', 'SOME GUY!', "HE'S GOOD!"] } },
    { id: 'drink', q: [['yn', 'ANOTHER DRINK?'], ['yn', 'YOU WANT ANYTHING?'], ['say', 'I NEED WATER.']],
      a: { yn: ['YES!', "I'M GOOD!", 'WATER!', "YOU'RE BUYING!"], say: ['BAR!', 'OVER THERE!', 'GET ME ONE!'] },
      n: [['WHAT DO YOU WANT?', ['SURPRISE ME!', 'THE PINK ONE!', 'WATER!']]], back: ['...I really need that drink now.'] },
    { id: 'jess', q: [['where', "WHERE'S JESS?"], ['yn', 'HAVE YOU SEEN JESS?']],
      a: { where: ['BAR!', 'BATHROOM LINE!', 'DANCING!', 'WHO?'], yn: ['NO!', 'SHE LEFT!', 'BAR, I THINK!'] },
      n: [['THERE IS ONE BAR!', ['THAT ONE THEN!', 'OH! YEAH!', 'WHAT?']]] },
    { id: 'loud', q: [['say', "IT'S SO LOUD!"], ['yn', 'OUTSIDE FOR A SEC?']],
      a: { say: ['WHAT?', "IT'S A CLUB!", 'I KNOW!'], yn: ['ONE MORE SONG!', 'YES!', 'NO!'] } },
  ],
};
/* how different people answer, per kind of question */
const PERSONA_ANS = {
  rude: { when: ['Do I look like a clock?', 'Figure it out.'], where: ['Somewhere. Not my problem.', 'Look around.'], yn: ['How would I know?', 'Why are you asking me?'], what: ['No idea. Don\'t care.', 'Ask someone else.'], how: ['Why do you care?', 'Fine. Whatever.'], who: ['Not me.', 'Who cares?'], say: ['Okay?', 'Cool story.', 'And?'] },
  quiet: { when: ['Dunno.', 'Later, maybe.'], where: ['Over there.', 'Not sure.'], yn: ['Maybe.', 'Mm. No.', 'Yeah.'], what: ['Dunno.', 'Hm.'], how: ['Fine.', 'Okay.'], who: ['Dunno.'], say: ['Mm.', 'Yeah.', 'Huh.'] },
  distracted: { yn: ['Sorry, what? Oh. Yeah. Probably.'], when: ['Hm? Oh, uh, later?'], say: ['Sorry, what? I was looking at something.', 'Huh? Yeah.'] },
  funny: { say: ['Riveting.', 'Put that on my tombstone.', 'Breaking news.'], yn: ['Ask me after my nap.', 'The answer is always maybe.'] },
};
const SWITCH = ['Anyway.', 'Oh, hey, totally different thing.', 'Speaking of which...', 'Oh, that reminds me.', 'Anyway, um.', 'Wait, did I tell you?'];
/* things people say while they're doing something */
const DOING = {
  dog: ['Slow down, buddy.', 'Leave it. LEAVE IT.', 'Good boy.', 'No, we are not chasing that.', 'Heel. Heel! Ugh.'],
  dance: ['WOO!', 'This part!', 'I love this part!', "Don't stop!", 'One more song!'],
  flashlight: ['Batteries are dying.', 'Can barely see a thing.', 'Hold on, let me point this over there.'],
  winter: ["It's freezing.", 'My fingers are numb.', 'Should\'ve worn gloves.', 'I can see my breath.'],
  autumn: ['Leaves everywhere.', 'Getting dark so early now.', 'Smells like bonfires.'],
  spring: ['Everything\'s blooming.', 'My allergies are killing me.', 'Finally warm out.'],
  summer: ["It's so hot.", 'I\'m melting.', 'Need some shade.'],
  night: ["It's so dark out here.", 'Should\'ve brought a flashlight.', 'Streetlight\'s out again.'],
};
