/* =========================================================
   CONVERSATIONS. Every opener has a type, and answers are grouped by that type, so a reply always fits what was
   actually said:  yn = yes/no question, when, where, what, how, who, say = a statement (gets a reaction).
   n = follow-up exchanges: [what the first person says next, [ways the other one answers it]]. Any of them can be
   picked, in any order, so a talk can run for a while or stop after one line.
   back = how someone brings the topic up again later, once the danger has passed.
   "#tag" opens a thread something later can close ("I swear something's weird tonight.#weird" -> "SEE? I TOLD YOU.").
   ========================================================= */
const TALK = {
  generic: [
    { id: 'phone', q: [['say', "My phone's almost dead."], ['say', "Ugh, my battery's at like five percent."], ['yn', 'You got a charger on you?'], ['yn', 'Can I borrow your charger later?']],
      a: { say: ['Mine too.', "Should've charged it last night.", "There's a charger in the car.", 'Put it on low power mode.', 'Classic.'], yn: ["In the car, yeah.", 'Nope, sorry.', "Not one that fits yours.", 'Yeah, remind me later.', "Mine's broken, so no."] },
      n: [["I need it for the bus times.", ["Just ask someone.", "The bus is late anyway.", "I know them by heart. Kind of."]], ["Who are you texting anyway?", ["Nobody.", "My sister.", "None of your business."]]] },
    { id: 'tired', q: [['say', "I'm so tired."], ['yn', 'Did you sleep at all last night?'], ['say', "I could fall asleep standing up."], ['how', 'How are you even awake right now?']],
      a: { say: ['Same.', 'Go to bed earlier then.', 'Coffee. Seriously.', 'You say that every day.', 'Long week?'], yn: ['Like four hours.', 'Not really, no.', 'Barely.', 'Yeah, actually. First time in ages.'], how: ['Spite.', 'Three coffees.', 'I am not awake.', 'Honestly? No idea.'] },
      n: [['The neighbors were up till two again.', ['Call someone about it.', "That's so annoying.", 'Doing what?']], ["I'm going to bed the second I get home.", ['Same.', "You won't.", "No you're not."]]] },
    { id: 'time', q: [['what', 'What time is it?'], ['what', 'You got the time?'], ['yn', 'Is it four yet?']],
      a: { what: ['Almost four.', 'About quarter past three.', 'No idea, my phone died.', 'Ten to four.', 'A little after four.'], yn: ['Almost.', 'Not yet.', 'Yeah, just passed four.', 'I don\'t know. My phone died.'] },
      n: [["We're gonna be late.", ['Yeah, we should move.', 'Then walk faster.', 'We\'ve still got a few minutes.']]] },
    { id: 'hungry', q: [['say', "I'm starving."], ['yn', 'You hungry?'], ['what', 'What do you want to eat later?']],
      a: { say: ['Same.', 'Already?', 'There\'s a granola bar in my bag.', 'We can grab something soon.'], yn: ['Yeah, kinda.', 'Not really.', 'A little.', 'I could eat.'], what: ['Burgers sound good.', 'I don\'t care. You pick.', 'Something cheap.', 'Maybe tacos?'] },
      n: [['Burgers?', ['I\'m down.', 'Again?', 'Sure, why not.']], ['You pick this time.', ['Okay, tacos.', 'Fine, but don\'t complain about my choice.', 'Give me a second to think.']]], back: ["Okay, I\'m definitely hungry now."] },
    { id: 'weather', q: [['yn', 'Think it\'s gonna rain?'], ['say', 'Sky looks like it\'s about to open up.'], ['say', 'Weather turned fast.']],
      a: { yn: ['Probably.', 'Hope not.', 'Looks like it.', 'I didn\'t check.'], say: ['Yeah, it changed quick.', 'I noticed.', 'We should probably head in soon.', 'Of course it did.'] },
      n: [['I didn\'t bring a jacket.', ['Neither did I.', 'You can borrow mine if it starts.', 'Then let\'s not stay out too long.']]] },
    { id: 'weekend', q: [['what', 'What are you doing this weekend?'], ['yn', 'You doing anything this weekend?'], ['say', 'I need this weekend so bad.']],
      a: { what: ['Probably sleeping.', 'My cousin\'s wedding.', 'Nothing, hopefully.', 'I\'m moving, unfortunately.'], yn: ['Not really.', 'Yeah, family stuff.', 'Maybe. Depends.', 'Working, unfortunately.'], say: ['Same.', 'Almost there.', 'Seriously.', 'This week has been dragging.'] },
      n: [['Want to do something Saturday?', ['Yeah, what did you have in mind?', 'Can\'t Saturday, sorry.', 'Maybe. Text me later.']]] },
    { id: 'weird', q: [['say', "I swear something's weird tonight.#weird"], ['say', 'Does it feel weird out here or is that just me?#weird'], ['say', 'Got a bad feeling about today.#weird']],
      a: { say: ["It's just you.", "You always say that.", "Yeah, actually. A little.", "Relax.", "What kind of weird?"] },
      n: [['I dunno. Too quiet.', ["You're being paranoid.", 'Yeah, it is quiet.', "Don't say that."]]] },
  ],
  field: [
    { id: 'lost', q: [['yn', 'Are we lost?'], ['where', 'Which way did we come in?'], ['where', 'Where was that gate again?']],
      a: { yn: ['Maybe a little.', 'No, I know where we are.', 'I think so.', 'Not lost. Just... turned around.'], where: ['Back that way, I think.', 'Past the fence.', 'Toward the tree line.', 'Honestly, I lost track.'] },
      n: [['You said that ten minutes ago.', ['I know. I\'m less confident now.', 'Then you pick a direction.', 'Okay, yeah, we might be lost.']], ['My feet are killing me.', ['Same.', 'We can stop for a minute.', 'We\'re finding the way back first.']]], back: ['Okay... where was that gate again?'] },
    { id: 'deer', q: [['yn', 'Seen any deer yet?'], ['say', 'There were deer here last time.']],
      a: { yn: ['One, by the trees.', 'Not yet.', "You're too loud for deer.", 'Something big ran off earlier.'], say: ['Maybe they moved.', 'Shh, then.', 'At dusk, probably.'] },
      n: [['They\'re usually out around sunset.', ['Then we wait.', 'We\'ll be gone by then.', 'Cool.']]] },
    { id: 'stars', q: [['say', 'You can actually see stars out here.'], ['yn', 'Is that bright one a planet?']],
      a: { say: ['Yeah. No city lights out here.', 'It\'s nice, actually.', 'Way more than you can see in town.'], yn: ['Might be Venus.', 'I think that\'s a plane.', 'No idea. Could be.'] },
      n: [["It's blinking.", ['Then it\'s probably a plane.', 'Yeah, okay, that\'s a plane.', 'Good catch.']]] },
    { id: 'fence', q: [['yn', 'Are we even allowed past that fence?'], ['say', 'I think this is private land.']],
      a: { yn: ['Probably not.', "Nobody's gonna check.", 'There was a sign.', "Didn't see a sign."], say: ['So?', "Then let's not get caught.", "It's a field. Who cares."] },
      n: [['What did the sign say?', ["Didn't read it.", "No trespassing, I think.", 'Something about dogs.']]] },
  ],
  meadow: [
    { id: 'lake', q: [['yn', 'You actually getting in?'], ['yn', 'Want to go in the lake?'], ['say', "Lake looks nice today."]],
      a: { yn: ['Maybe in a minute.', 'Yeah, but I\'m not going past my knees.', 'No chance.', 'Only if you go first.'], say: ['Yeah, it does.', 'It looks freezing though.', 'Makes me want to jump in.', 'Way nicer than last time.'] },
      n: [['Think the water\'s cold?', ['Definitely.', 'Probably at first.', 'Only one way to find out.']], ['Race you to the dock.', ['You\'re on.', 'Give me a second.', 'Absolutely not.']]] },
    { id: 'bugs', q: [['say', 'I should\'ve brought bug spray.'], ['say', 'Something keeps biting me.'], ['yn', 'You got bug spray?']],
      a: { say: ['Told you.', "It's the lake.", "Don't scratch it.", 'They like you more than me.'], yn: ['In my bag. Somewhere.', 'Ran out.', 'Yep. Hold still.', 'Nope. Sorry.'] },
      n: [['You did not tell me.', ['In the car. Twice.', 'I definitely did.', 'Okay, maybe I thought it.']]] },
    { id: 'fire', q: [['say', "Fire's getting low."], ['yn', 'Should we put more wood on?'], ['who', 'Whose turn is it to get wood?']],
      a: { say: ['I\'ll get some.', 'Let it go out.', 'In a sec.'], yn: ['Yeah, go for it.', 'Wood\'s all damp.', 'Let it die, I\'m tired.'], who: ['Yours.', "Not mine, I went last time.", "Nobody's. Let it go out."] },
      n: [['There\'s dry stuff under the tarp.', ['Then you get it.', 'Smart.', 'Okay, fine, I\'ll go.']]] },
    { id: 'trail', q: [['yn', 'Does this trail loop back?'], ['how', 'How much longer is this trail?'], ['where', 'Where does this trail come out?']],
      a: { yn: ['Eventually.', "It's supposed to.", 'No idea, I\'m following you.'], how: ['Mile? Maybe two.', "Not long.", 'Longer than you want.'], where: ['By the car park.', 'Back at the tents, I think.', 'No idea.'] },
      n: [["The map said it loops.", ["The map's from 2009.", 'Then it loops.', 'Maps lie.']]], back: ['So does this trail loop back or not?'] },
    { id: 'frogs', q: [['say', 'The frogs are so loud tonight.'], ['yn', 'Hear the frogs?']],
      a: { say: ['Means rain, I think.', 'I like it.', "I can't sleep with that.", 'It\'s mating season or something.'], yn: ['Hard not to.', 'Yeah, it\'s nice.', 'Is that a frog? Sounded like a duck.'] } },
  ],
  town: [
    { id: 'pizza', q: [['when', 'What time does that pizza place open?'], ['when', 'Do you remember when the pizza shop opens?'], ['yn', 'Is the pizza place open yet?'], ['yn', 'Think the pizza place is open?']],
      a: { when: ['Eleven, I think.', 'Pretty sure it\'s eleven.', 'Maybe noon?', 'I don\'t remember.'], yn: ['I think so.', 'Probably not yet.', 'It should be by now.', 'Not sure. Check your phone.', 'It was open when I passed it earlier.'] },
      n: [['You want to grab some after this?', ['Yeah, I could eat.', 'Sure.', 'Not from that place.', 'If you\'re buying.']], ['Their garlic knots are actually good.', ['Yeah, those are solid.', 'They\'re okay.', 'Last time they messed up my order.']]], back: ['So... pizza after this?'] },
    { id: 'traffic', q: [['say', "Traffic's been awful all day."], ['how', 'How long did it take you to get here?'], ['what', 'How\'d you get here?']],
      a: { say: ['Yeah, the roadwork is killing traffic.', 'Tell me about it.', 'It\'s been backed up since this morning.', 'I should\'ve walked.'], how: ['Almost forty minutes.', 'Way too long.', 'Like twenty minutes.', 'Not long. I walked.'], what: ['Drove. Parked a few blocks over.', 'Took the bus.', 'Walked.', 'Got dropped off.'] },
      n: [['They\'ve been digging up that road for months.', ['I know. It never ends.', 'Same stretch too.', 'I don\'t even know what they\'re fixing anymore.']]] },
    { id: 'store', q: [['yn', 'Corner store still open?'], ['what', 'Need anything from the store?'], ['when', 'When does the corner store close?']],
      a: { yn: ['Should be.', 'Yeah, I think so.', 'I think it closed already.', 'It was open when I passed it.'], what: ['Milk, maybe.', 'Chips.', 'I\'m good, thanks.', 'Batteries, actually.'], when: ['Ten, I think.', 'Around eleven.', 'Pretty late.', 'I don\'t remember.'] },
      n: [['Get me something sweet.', ['Like what?', 'Sure. Any preference?', 'Okay, I\'ll grab something.']]], back: ['We still need that milk, by the way.'] },
    { id: 'alley', q: [['yn', 'You still cut through that alley?'], ['say', "Don't cut through the alley tonight."]],
      a: { yn: ['Only when I\'m late.', "It's faster.", 'Not after dark.'], say: ['Why not?', "It's fine.", 'Okay, okay.'] },
      n: [["It's gross back there.", ['It\'s two minutes faster.', 'Fair.', 'Rats don\'t bother me.']]] },
    { id: 'rent', q: [['yn', 'Did your rent go up too?'], ['say', 'Landlord raised the rent again.']],
      a: { yn: ["Don't. Don't start.", 'Of course it did.', 'Mine\'s locked in till spring.'], say: ['Again?', "That's insane.", 'Move in with me. Kidding.'] },
      n: [['I might have to move.', ['Where?', "Don't, I'll miss you.", 'Everywhere\'s the same.']]] },
  ],
  maze: [
    { id: 'way', q: [['yn', 'Did we already go this way?'], ['where', 'Which way is out?'], ['say', 'I swear we passed this hedge.']],
      a: { yn: ['Twice.', 'No? Maybe.', 'Every hedge looks the same.'], where: ['Left. I think.', 'Right. Definitely right. Maybe.', 'No idea.'], say: ['They all look the same.', 'We did.', "It's a maze. That's the point."] },
      n: [['You said that last time.', ['Then you pick.', "And I'll be right eventually.", 'Fine. Left.']]], back: ['Okay, seriously, which way is out?'] },
    { id: 'center', q: [['what', "What's even in the middle?"], ['yn', 'Is there a prize in the middle or something?']],
      a: { what: ['A bench, probably.', 'Nothing. It\'s a maze.', 'A statue, I heard.'], yn: ['Bragging rights.', 'Pretty sure no.', 'A sense of accomplishment.'] } },
    { id: 'creepy', q: [['say', 'This place is creepy at night.#weird'], ['yn', 'Why did we come here after dark?']],
      a: { say: ['It\'s fine.', 'Yeah, it\'s a lot.', 'Don\'t start.'], yn: ['Tickets were cheaper.', 'It was your idea.', "Seemed fun at the time."] } },
  ],
  farm: [
    { id: 'fence', q: [['say', 'Fence by the pigs needs fixing.'], ['yn', 'Did you see the fence by the pigs?']],
      a: { say: ['Which part?', 'Again?', 'After lunch.', 'I fixed that last week. I thought.'], yn: ['The broken bit? Yeah.', 'No, what happened?', 'Saw it. Ignored it.'] },
      n: [['The corner post. It\'s leaning.', ['I\'ll get the hammer.', 'Tomorrow.', 'That post\'s been leaning for years.']], ['The pigs keep pushing on it.', ['They\'re smarter than us.', 'Then we need a new one.', 'I\'ll move the trough.']]] },
    { id: 'hens', q: [['say', 'Hens are restless today.'], ['yn', 'Hear the chickens going off?']],
      a: { say: ['Storm coming, maybe.', 'Or a fox.', "They're always restless.", "I'll check the coop."], yn: ['Since this morning.', 'Probably a fox.', "I didn't hear anything."] },
      n: [['Something\'s got them spooked.#weird', ['Probably a fox.', "I'll take a look.", "They're chickens. Everything spooks them."]]] },
    { id: 'feed', q: [['yn', 'You feed the animals yet?'], ['yn', 'Did everything get fed this morning?'], ['who', 'Who fed the animals this morning?']],
      a: { yn: ['Yeah, this morning.', 'Not yet.', 'I thought you already did.', 'Most of them. I still need to do the pigs.'], who: ['I did.', 'Your dad did.', 'I thought you did.', 'Nobody yet, I think.'] },
      n: [['They\'re acting starved.', ['They always do.', 'I\'ll check them again.', 'Don\'t let them fool you.']]] },
    { id: 'tractor', q: [['yn', 'Tractor still making that noise?'], ['say', 'Tractor\'s making that noise again.']],
      a: { yn: ['Worse.', 'Kicked it. It helped.', 'Haven\'t started it today.'], say: ['Kick it.', "It's always done that.", "I'll call Dave."] } },
  ],
  park: [
    { id: 'dog', q: [['say', "He's loving this."], ['yn', 'Is he always this hyper?'], ['how', 'How old is he now?']],
      a: { say: ['Look at him go.', 'He\'d chase anything.', 'Wait till he sees a squirrel.'], yn: ['Every single day.', 'Only around ducks.', 'Only outside.'], how: ['Three.', 'Almost two.', 'Seven, believe it or not.'] },
      n: [['Can I pet him?', ['Sure, he loves it.', 'He might lick you.', 'He bites. Kidding.']]] },
    { id: 'ducks', q: [['say', 'Those ducks are following us.'], ['yn', 'Did you bring anything for the ducks?']],
      a: { say: ['They think we have food.', 'They do that to everyone.', 'Ignore them or they\'ll keep following us.'], yn: ['No. We probably shouldn\'t feed them anyway.', 'I brought a little birdseed.', 'Nope.', 'Yeah, but not bread.'] },
      n: [['Why not bread?', ['It\'s not good for them, apparently.', 'Birdseed\'s better.', 'I read it can mess with their diet.']]] },
    { id: 'bench', q: [['yn', 'Wanna sit for a bit?'], ['say', 'My legs are done.']],
      a: { yn: ['Sure.', 'In a sec.', 'That bench is wet.', 'If we can find a dry one.'], say: ['We walked like a mile.', 'Sit, then.', 'Same.'] } },
    { id: 'jog', q: [['yn', 'You still running every morning?'], ['how', 'How many laps did you do?']],
      a: { yn: ['Most mornings.', 'I walk now. It counts.', 'Skipped today.'], how: ['Three.', 'One and a half.', 'Don\'t ask.'] } },
  ],
  pool: [
    { id: 'water', q: [['say', "Water's actually nice today."], ['yn', 'You getting in?'], ['yn', 'Are you coming in or not?']],
      a: { say: ['Yeah, it\'s not bad.', 'Told you.', 'Way better than yesterday.', 'Still feels cold to me.'], yn: ['Yeah, give me a second.', 'In a minute.', 'Nope, I\'m good.', 'Maybe. Let me test it first.'] },
      n: [['Cold?', ['A little at first.', 'Not really.', 'Yeah, but you get used to it.']], ['Come on, get in.', ['I\'m coming.', 'Give me a minute.', 'Not happening.']]] },
    { id: 'sunscreen', q: [['yn', 'You bring sunscreen?'], ['yn', 'Do you have sunscreen?'], ['yn', 'Please tell me you brought sunscreen.']],
      a: { yn: ['Yeah, it\'s in my bag.', 'I think so. Check the side pocket.', 'No, I forgot it.', 'I ran out this morning.'] },
      n: [['I think I\'m already burning.', ['Then put some on now.', 'Get in the shade for a bit.', 'Yeah, your shoulders are getting red.']]] },
    { id: 'snacks', q: [['yn', 'Snack bar open?'], ['when', 'When does the snack bar close?'], ['say', 'I want a slushie so bad.']],
      a: { yn: ['Line\'s huge.', 'Yeah, just opened.', "Closed for lunch, I think."], when: ['Five.', 'Like four?', 'No idea.'], say: ['Get me one.', 'Blue one.', 'Brain freeze incoming.'] },
      n: [['Cherry or blue?', ['Blue. Obviously.', 'Cherry.', 'Both.']]], back: ['...still want that slushie.'] },
    { id: 'lifeguard', q: [['yn', 'Is the lifeguard even awake?'], ['say', "Lifeguard's been on his phone all day."]],
      a: { yn: ['Barely.', 'He blew the whistle earlier.', 'He\'s wearing sunglasses, who knows.'], say: ['Ha. Yeah.', 'Not our problem.', 'Must be nice.'] } },
  ],
  office: [
    { id: 'meeting', q: [['when', 'When is the meeting again?'], ['yn', 'You going to the meeting?'], ['yn', 'Are you sitting in on the three o\'clock?']],
      a: { when: ['Three.', 'They pushed it to four.', 'I think it\'s at three.', 'Tomorrow morning, unless they changed it again.'], yn: ['Yeah, I have to.', 'Unfortunately.', 'No, I\'m skipping it.', 'I think so.'] },
      n: [['What\'s it even about?', ['The new system.', 'Budget stuff, I think.', 'No idea. I stopped reading after the first email.']]] },
    { id: 'printer', q: [['yn', 'Is the printer working?'], ['say', 'Printer\'s broken again.']],
      a: { yn: ['If you kick it.', 'Out of toner.', 'Try the one upstairs.', 'It was never fixed.'], say: ['Shocking.', "Did you call IT?", 'It hates you specifically.'] },
      n: [['I need this printed by noon.', ['Email it.', 'Good luck.', 'Upstairs one works.']]] },
    { id: 'coffee', q: [['yn', 'Coffee?'], ['yn', 'Want me to grab you coffee?'], ['say', 'I need coffee before I talk to anyone.']],
      a: { yn: ['Please.', 'Yeah, thanks.', 'I\'m good.', 'Only if the pot is fresh.'], say: ['Same.', 'You\'re already talking to me.', 'There\'s a fresh pot in the kitchen.', 'That makes two of us.'] },
      n: [['The machine\'s out again.', ['Of course it is.', 'Try the kitchen upstairs.', 'Then I\'m going home.']]], back: ['...I still need that coffee.'] },
    { id: 'fridge', q: [['say', 'Someone ate my yogurt again.'], ['who', 'Who keeps taking food from the fridge?']],
      a: { say: ['Not me.', 'Label it.', 'Probably Kevin.'], who: ['Kevin.', 'Not me, I swear.', "Nobody knows. It's a mystery."] },
      n: [['It had my name on it.', ['Then it was definitely Kevin.', 'Huh.', 'Start hiding it.']]] },
    { id: 'friday', q: [['yn', 'Is it Friday yet?'], ['say', 'This week is taking forever.']],
      a: { yn: ['Not even close.', 'I wish.', 'Feels like it should be.', 'Don\'t remind me.'], say: ['Seriously.', 'I know.', 'Every day feels like Monday here.', 'It really is.'] } },
  ],
  checker: [
    { id: 'who', q: [['who', 'Who even built this place?'], ['yn', 'Is this an art thing?']],
      a: { who: ['Some rich guy.', 'No idea.', 'Same people who did the big sculpture downtown.'], yn: ['Has to be.', 'I think so.', 'Looks like a game show.'] } },
    { id: 'photo', q: [['yn', 'Take my picture by the king?'], ['yn', 'Get a photo with the horse?']],
      a: { yn: ['Hold still.', 'One sec.', 'Your eyes were closed. Again.', 'Sure.'] } },
  ],
  crew: [
    { id: 'suit', q: [['yn', 'Suit pressure look okay?'], ['yn', 'Everything green on my suit?'], ['how', 'How\'s your oxygen?']],
      a: { yn: ['Yeah, all green.', 'Looks good from here.', 'Pressure\'s a little low. Keep an eye on it.', 'Hold on... yeah, you\'re good.'], how: ['Seventy percent.', 'Fine for now.', 'Getting low. I\'ll head back soon.', 'About half.'] },
      n: [['Base wants us back in an hour.', ['Copy.', 'That gives us time.', 'Tell them we\'re wrapping up.']]] },
    { id: 'samples', q: [['how', 'How many samples left?'], ['yn', 'We done sampling yet?']],
      a: { how: ['Six more.', 'Two. Then lunch.', 'Lost count.'], yn: ['Nearly.', 'Not even close.', 'Base says four more.'] }, back: ['...base still wants those samples.'] },
    { id: 'home', q: [['yn', 'Talked to your family yet?'], ['when', "When's the next call home?"]],
      a: { yn: ['Yeah, last night.', 'Not yet. Signal\'s been awful.', 'A few days ago.', 'Tried, but the call dropped.'], when: ['Thursday.', 'Tonight, hopefully.', 'Whenever the dish starts working again.'] } },
  ],
  station: [
    { id: 'shift', q: [['when', 'When are you off?'], ['how', 'How long do you have left?']],
      a: { when: ['Midnight.', 'In about twenty minutes.', 'I was supposed to be off an hour ago. I\'m covering.', 'Not until morning.'], how: ['About twenty minutes.', 'A couple hours.', 'Too long.', 'I\'m on a double, so don\'t ask.'] },
      n: [['Want to swap Thursday?', ['Sure.', 'Only if you take Saturday.', 'No way.']]] },
    { id: 'maint', q: [['yn', 'Did maintenance ever fix that panel?'], ['say', "That panel's sparking again."]],
      a: { yn: ['Nope.', 'They said Tuesday.', 'Which panel?'], say: ["Don't touch it.", 'Log it.', "It's been doing that all week."] },
      n: [['The one by the lab door.', ['Oh, that one. No.', 'Still broken.', "I'll put in a ticket."]]] },
    { id: 'food', q: [['what', "What's for dinner?"], ['yn', 'Please tell me it\'s not the paste again.']],
      a: { what: ['Paste.', 'Rehydrated something.', "Mike's making curry. Allegedly."], yn: ['It\'s the paste.', 'Better. Rehydrated pasta.', 'Worse.'] } },
    { id: 'air', q: [['yn', 'Did you check the scrubbers?'], ['say', 'Air smells weird today.#weird']],
      a: { yn: ['Twice.', 'Doing it now.', "That's not my job."], say: ["That's Mike's lunch.", 'It always smells weird.', 'Log it.'] } },
  ],
  bunker: [
    { id: 'shift', q: [['who', "Who's on after us?"], ['say', 'Shift change in ten.']],
      a: { who: ['Davis. Ugh.', 'Nobody, we\'re on doubles.', 'The new guy.'], say: ['Finally.', 'Twenty, actually.', "Don't get excited."] } },
    { id: 'radio', q: [['yn', 'Hear anything on the radio?'], ['say', "Radio's been quiet."]],
      a: { yn: ['Static.', 'Nothing.', 'Someone humming. Weird.'], say: ["Quiet's good.", 'Too quiet.#weird', 'Turn it up.'] } },
    { id: 'cards', q: [['yn', 'Cards after shift?'], ['say', 'You owe me from last night.']],
      a: { yn: ['Deal.', 'Not with you. You cheat.', 'Double or nothing.'], say: ["I don't owe you anything.", 'Double or nothing?', 'Put it on my tab.'] } },
    { id: 'food', q: [['what', "What's for chow?"], ['yn', 'Please not the beans again.']],
      a: { what: ['Beans.', 'Mystery stew.', 'Same as yesterday.'], yn: ['Beans.', 'Worse. Stew.', 'Better than nothing.'] } },
  ],
  club: [
    { id: 'song', q: [['say', 'I LOVE THIS SONG!'], ['who', "WHO'S DJING?"], ['say', 'THIS SONG!']],
      a: { say: ['WHAT?', 'SAME!', "IT'S THE SAME SONG!", 'YEAH!'], who: ['NO IDEA!', 'SOME GUY!', "HE'S GOOD!"] } },
    { id: 'drink', q: [['yn', 'ANOTHER DRINK?'], ['yn', 'YOU WANT ANYTHING?'], ['say', 'I NEED WATER.']],
      a: { yn: ['YES!', "I'M GOOD!", 'WATER!', "YOU'RE BUYING!"], say: ['BAR!', 'OVER THERE!', 'GET ME ONE!'] },
      n: [['WHAT DO YOU WANT?', ['SURPRISE ME!', 'THE PINK ONE!', 'WATER!']]], back: ['...I really need that drink now.'] },
    { id: 'jess', q: [['where', "WHERE'S JESS?"], ['yn', 'HAVE YOU SEEN JESS?']],
      a: { where: ['BAR!', 'BATHROOM LINE!', 'DANCING!', 'WHO?'], yn: ['NO!', 'SHE LEFT!', 'BAR, I THINK!'] },
      n: [['THERE IS ONE BAR!', ['THAT ONE THEN!', 'OH! YEAH!', 'WHAT?']]] },
    { id: 'loud', q: [['say', "IT'S SO LOUD!"], ['yn', 'OUTSIDE FOR A SEC?']],
      a: { say: ['WHAT?', "IT'S A CLUB!", 'I KNOW!'], yn: ['ONE MORE SONG!', 'YES!', 'NO!'] } },
  ],
};
/* how different people answer, per kind of question */
const PERSONA_ANS = {
  /* Keep persona overrides deliberately broad. These can replace many different topic-specific answers,
     so they should sound like believable reactions without pretending to know details they were never given. */
  rude: {
    when: ['I don\'t know. Check.', 'Why are you asking me?'],
    where: ['No idea.', 'Go look.'],
    yn: ['How would I know?', 'Probably. Whatever.'],
    what: ['No idea.', 'Ask somebody else.'],
    how: ['I don\'t know.', 'Why do you care?'],
    who: ['Not me.', 'No clue.'],
    say: ['Okay?', 'And?', 'Good to know.']
  },
  quiet: {
    when: ['Not sure.', 'I don\'t know.'],
    where: ['Not sure.', 'Over there, I think.'],
    yn: ['Maybe.', 'Yeah, I think so.', 'No, I don\'t think so.'],
    what: ['I don\'t know.', 'Not sure.'],
    how: ['Not sure.', 'I don\'t know.'],
    who: ['No idea.', 'Not sure.'],
    say: ['Yeah.', 'Mm.', 'I know.']
  },
  distracted: {
    yn: ['Sorry, what? Uh... maybe.', 'Huh? Yeah, I think so.'],
    when: ['Sorry, what? I\'m not sure.', 'Uh... I don\'t remember.'],
    where: ['Wait, what? I don\'t know.', 'Sorry. Over there, maybe?'],
    what: ['Huh? Sorry, I wasn\'t listening.', 'I don\'t know.'],
    how: ['Sorry, what was the question?', 'Uh... not sure.'],
    who: ['Who? Sorry, I missed that.', 'No idea.'],
    say: ['Sorry, I was looking at something.', 'Huh? Yeah.']
  },
  funny: {
    /* Only override types where a generic joke can still make sense. Specific who/what/when/where/how
       questions keep their topic-specific answer instead of getting a random punchline. */
    say: ['Huge development.', 'That changes everything.', 'Tragic.'],
    yn: ['I\'m gonna go with maybe.', 'Sure. Why not?']
  },
};
const SWITCH = ['Anyway.', 'Oh, hey, totally different thing.', 'Speaking of which...', 'Oh, that reminds me.', 'Anyway, um.', 'Wait, did I tell you?'];
/* things people say while they're doing something */
const DOING = {
  dog: ['Slow down, buddy.', 'Leave it. LEAVE IT.', 'Good boy.', 'No, we are not chasing that.', 'Heel. Heel! Ugh.'],
  dance: ['WOO!', 'This part!', 'I love this part!', "Don't stop!", 'One more song!'],
  flashlight: ['Batteries are dying.', 'Can barely see a thing.', 'Hold on, let me point this over there.'],
  winter: ["It's freezing.", 'My fingers are numb.', 'Should\'ve worn gloves.', 'I can see my breath.'],
  autumn: ['Leaves everywhere.', 'Getting dark so early now.', 'Smells like bonfires.'],
  spring: ['Everything\'s blooming.', 'My allergies are killing me.', 'Finally warm out.'],
  summer: ["It's so hot.", 'I\'m melting.', 'Need some shade.'],
  night: ["It's so dark out here.", 'Should\'ve brought a flashlight.', 'Streetlight\'s out again.'],
};
